import daisyui from 'daisyui'

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./layouts/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        light: {
          "primary": "#570df8",
          "primary-content": "#ffffff",
          "secondary": "#f000b8",
          "secondary-content": "#ffffff",
          "accent": "#37cdbe",
          "accent-content": "#163835",
          "neutral": "#3d4451",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f2f2f2",
          "base-300": "#e5e5e5",
          "base-content": "#1f2937",
          "info": "#3abff8",
          "info-content": "#002b3d",
          "success": "#36d399",
          "success-content": "#003320",
          "warning": "#fbbd23",
          "warning-content": "#382800",
          "error": "#f87272",
          "error-content": "#470000",
        },
        dark: {
          "primary": "#661ae6",
          "primary-content": "#ffffff",
          "secondary": "#d926aa",
          "secondary-content": "#ffffff",
          "accent": "#1fb2a5",
          "accent-content": "#ffffff",
          "neutral": "#2a323c",
          "neutral-content": "#a6adbb",
          "base-100": "#1d232a",
          "base-200": "#191e24",
          "base-300": "#15191e",
          "base-content": "#a6adbb",
          "info": "#3abff8",
          "info-content": "#002b3d",
          "success": "#36d399",
          "success-content": "#003320",
          "warning": "#fbbd23",
          "warning-content": "#382800",
          "error": "#f87272",
          "error-content": "#470000",
        },
      },
    ],
  },
}