// Imported from tombatossals/chords-db at df06fa7b425cf5fd29485ff6591236b3557e3fac.
// MIT © 2016 David Rubert. See public/licenses/chords-db.txt.
// Generated by scripts/import-guitar-library.mjs. Frets/barres are absolute.
import type { LibraryPosition } from "./ukulele-shapes.ts";
export const GUITAR_SHAPES: Record<string, LibraryPosition[]> = {
  "C:major": [
    { frets: [null, 3, 2, 0, 1, 0], fingers: [0, 3, 2, 0, 1, 0], barres: [] },
    { frets: [null, 3, 5, 5, 5, 3], fingers: [0, 1, 2, 3, 4, 1], barres: [3] },
    {
      frets: [null, null, 5, 5, 5, 8],
      fingers: [0, 0, 1, 1, 1, 4],
      barres: [5],
    },
    { frets: [8, 10, 10, 9, 8, 8], fingers: [1, 3, 4, 2, 1, 1], barres: [8] },
  ],
  "C:minor": [
    { frets: [null, 3, 1, 0, 1, 3], fingers: [0, 3, 2, 0, 1, 4], barres: [] },
    { frets: [3, 3, 5, 5, 4, 3], fingers: [1, 1, 3, 4, 2, 1], barres: [3] },
    {
      frets: [8, 6, 5, 5, null, null],
      fingers: [4, 2, 1, 1, 0, 0],
      barres: [5],
    },
    { frets: [8, 10, 10, 8, 8, 8], fingers: [1, 3, 4, 1, 1, 1], barres: [8] },
  ],
  "C:dim": [
    {
      frets: [null, 3, 1, null, 1, 2],
      fingers: [0, 4, 1, 0, 2, 3],
      barres: [],
    },
    {
      frets: [null, 3, 4, 5, 4, null],
      fingers: [0, 1, 2, 4, 3, 0],
      barres: [],
    },
    {
      frets: [8, 6, null, 8, 7, null],
      fingers: [3, 1, 0, 4, 2, 0],
      barres: [],
    },
    {
      frets: [null, null, 10, 11, null, 11],
      fingers: [0, 0, 1, 2, 0, 3],
      barres: [],
    },
  ],
  "C:dim7": [
    {
      frets: [null, null, 1, 2, 1, 2],
      fingers: [0, 0, 1, 3, 2, 4],
      barres: [],
    },
    { frets: [null, 3, 4, 2, 4, 2], fingers: [0, 2, 3, 1, 4, 1], barres: [2] },
    {
      frets: [8, null, 7, 8, 7, null],
      fingers: [2, 0, 1, 3, 1, 0],
      barres: [7],
    },
    {
      frets: [null, null, 10, 11, 10, 11],
      fingers: [0, 0, 1, 3, 1, 4],
      barres: [10],
    },
  ],
  "C:sus2": [
    { frets: [null, 3, 0, 0, 1, 3], fingers: [0, 3, 0, 0, 1, 4], barres: [] },
    { frets: [null, 3, 0, 0, 3, 3], fingers: [0, 1, 0, 0, 2, 3], barres: [] },
    { frets: [3, 3, 5, 5, 3, 3], fingers: [1, 1, 3, 4, 1, 1], barres: [3] },
    { frets: [8, null, 0, 7, 8, 8], fingers: [2, 0, 0, 1, 3, 4], barres: [] },
  ],
  "C:sus4": [
    { frets: [null, 3, 3, 0, 1, 1], fingers: [0, 3, 4, 0, 1, 1], barres: [1] },
    { frets: [3, 3, 5, 5, 6, 3], fingers: [1, 1, 2, 3, 4, 1], barres: [3] },
    { frets: [8, 8, null, 0, 6, 8], fingers: [2, 3, 0, 0, 1, 4], barres: [] },
    { frets: [8, 10, 10, 10, 8, 8], fingers: [1, 2, 3, 4, 1, 1], barres: [8] },
  ],
  "C:aug": [
    {
      frets: [null, 3, 2, 1, 1, null],
      fingers: [0, 3, 2, 1, 1, 0],
      barres: [1],
    },
    {
      frets: [null, 3, 6, 5, 5, null],
      fingers: [0, 1, 4, 2, 3, 0],
      barres: [],
    },
    { frets: [8, 7, 6, 5, 5, null], fingers: [4, 3, 2, 1, 1, 0], barres: [5] },
    {
      frets: [null, null, 10, 9, 9, 8],
      fingers: [0, 0, 4, 2, 3, 1],
      barres: [],
    },
  ],
  "C:6": [
    { frets: [null, 3, 2, 2, 1, 0], fingers: [0, 4, 2, 3, 1, 0], barres: [] },
    { frets: [null, 3, 5, 5, 5, 5], fingers: [0, 1, 3, 3, 3, 4], barres: [5] },
    {
      frets: [8, null, 7, 9, 8, null],
      fingers: [2, 0, 1, 4, 3, 0],
      barres: [],
    },
    {
      frets: [8, null, 10, 9, 10, 8],
      fingers: [1, 0, 3, 2, 4, 1],
      barres: [8],
    },
  ],
  "C:7": [
    { frets: [null, 3, 2, 3, 1, 0], fingers: [0, 3, 2, 4, 1, 0], barres: [] },
    { frets: [null, 3, 5, 3, 5, 3], fingers: [0, 1, 3, 1, 4, 1], barres: [3] },
    {
      frets: [null, null, 5, 5, 5, 6],
      fingers: [0, 0, 1, 1, 1, 2],
      barres: [5],
    },
    { frets: [8, 10, 8, 9, 8, 8], fingers: [1, 3, 1, 2, 1, 1], barres: [8] },
  ],
  "C:maj7": [
    { frets: [3, 3, 2, 0, 0, 0], fingers: [2, 3, 1, 0, 0, 0], barres: [] },
    { frets: [3, 3, 5, 4, 5, 3], fingers: [1, 1, 3, 2, 4, 1], barres: [3] },
    {
      frets: [null, null, 5, 5, 5, 7],
      fingers: [0, 0, 1, 1, 1, 4],
      barres: [5],
    },
    {
      frets: [null, null, 10, 12, 12, 12],
      fingers: [0, 0, 1, 3, 3, 3],
      barres: [12],
    },
  ],
  "C:m6": [
    { frets: [null, 3, 1, 2, 1, 3], fingers: [0, 3, 1, 2, 1, 4], barres: [1] },
    {
      frets: [null, 3, 5, null, 4, 5],
      fingers: [0, 1, 3, 0, 2, 4],
      barres: [],
    },
    { frets: [8, null, 7, 8, 8, 8], fingers: [2, 0, 1, 3, 3, 4], barres: [8] },
    { frets: [8, 10, 10, 8, 10, 8], fingers: [1, 2, 3, 1, 4, 1], barres: [8] },
  ],
  "C:m7": [
    {
      frets: [8, null, 8, 8, 8, null],
      fingers: [2, 0, 3, 3, 3, 0],
      barres: [8],
    },
    {
      frets: [null, 3, 1, 3, 4, null],
      fingers: [0, 2, 1, 3, 4, 0],
      barres: [],
    },
    { frets: [3, 3, 5, 3, 4, 3], fingers: [1, 1, 3, 1, 2, 1], barres: [3] },
    {
      frets: [null, null, 5, 5, 4, 6],
      fingers: [0, 0, 2, 3, 1, 4],
      barres: [],
    },
    { frets: [8, 10, 8, 8, 8, 8], fingers: [1, 3, 1, 1, 1, 1], barres: [8] },
  ],
  "C:m7b5": [
    {
      frets: [null, 3, 4, 3, 4, null],
      fingers: [0, 1, 3, 2, 4, 0],
      barres: [],
    },
    {
      frets: [null, null, 4, 5, 4, 6],
      fingers: [0, 0, 1, 2, 1, 4],
      barres: [4],
    },
    { frets: [8, 9, 10, 8, 11, 8], fingers: [1, 2, 3, 1, 4, 1], barres: [8] },
    {
      frets: [null, null, 10, 11, 11, 11],
      fingers: [0, 0, 1, 3, 3, 3],
      barres: [11],
    },
  ],
  "C:add9": [
    { frets: [null, 3, 2, 0, 3, 0], fingers: [0, 2, 1, 0, 3, 0], barres: [] },
    { frets: [null, 3, 0, 0, 3, 0], fingers: [0, 1, 0, 0, 3, 0], barres: [] },
    { frets: [8, 7, 0, 0, 8, 0], fingers: [2, 1, 0, 0, 3, 0], barres: [] },
    {
      frets: [null, null, 10, 9, 8, 10],
      fingers: [0, 0, 3, 2, 1, 4],
      barres: [],
    },
  ],
  "Db:major": [
    { frets: [null, 4, 3, 1, 2, 1], fingers: [0, 4, 3, 1, 2, 1], barres: [1] },
    { frets: [4, 4, 6, 6, 6, 4], fingers: [1, 1, 2, 3, 4, 1], barres: [4] },
    { frets: [9, 8, 6, 6, 6, 9], fingers: [3, 2, 1, 1, 1, 4], barres: [6] },
    { frets: [9, 11, 11, 10, 9, 9], fingers: [1, 3, 4, 2, 1, 1], barres: [9] },
  ],
  "Db:minor": [
    {
      frets: [null, 4, 2, 1, 2, null],
      fingers: [0, 4, 2, 1, 3, 0],
      barres: [],
    },
    { frets: [4, 4, 6, 6, 5, 4], fingers: [1, 1, 3, 4, 2, 1], barres: [4] },
    { frets: [9, 7, 6, 6, null, 9], fingers: [3, 2, 1, 1, 0, 4], barres: [6] },
    { frets: [9, 11, 11, 9, 9, 9], fingers: [1, 3, 4, 1, 1, 1], barres: [9] },
  ],
  "Db:dim": [
    {
      frets: [null, 4, 2, null, 2, 3],
      fingers: [0, 4, 1, 0, 2, 3],
      barres: [],
    },
    {
      frets: [null, 4, 5, 6, 5, null],
      fingers: [0, 1, 2, 4, 3, 0],
      barres: [],
    },
    {
      frets: [9, 7, null, 9, 8, null],
      fingers: [3, 1, 0, 4, 2, 0],
      barres: [],
    },
    {
      frets: [null, null, 11, 12, null, 12],
      fingers: [0, 0, 1, 2, 0, 3],
      barres: [],
    },
  ],
  "Db:dim7": [
    {
      frets: [null, null, 2, 3, 2, 3],
      fingers: [0, 0, 1, 3, 2, 4],
      barres: [],
    },
    { frets: [null, 4, 5, 3, 5, 3], fingers: [0, 2, 3, 1, 4, 1], barres: [3] },
    {
      frets: [9, null, 8, 9, 8, null],
      fingers: [2, 0, 1, 3, 1, 0],
      barres: [8],
    },
    {
      frets: [null, null, 11, 12, 11, 12],
      fingers: [0, 0, 1, 3, 2, 4],
      barres: [],
    },
  ],
  "Db:sus2": [
    { frets: [4, 4, 6, 6, 4, 4], fingers: [1, 1, 3, 4, 1, 1], barres: [4] },
    {
      frets: [9, 11, 11, null, 9, 11],
      fingers: [1, 2, 3, 0, 1, 4],
      barres: [9],
    },
    {
      frets: [11, 11, 11, 13, 14, 11],
      fingers: [1, 1, 1, 3, 4, 1],
      barres: [11],
    },
  ],
  "Db:sus4": [
    {
      frets: [null, 4, 4, 1, 2, null],
      fingers: [0, 3, 4, 1, 2, 0],
      barres: [],
    },
    { frets: [4, 4, 6, 6, 7, 4], fingers: [1, 1, 2, 3, 4, 1], barres: [4] },
    { frets: [9, 11, 11, 11, 9, 9], fingers: [1, 2, 3, 4, 1, 1], barres: [9] },
  ],
  "Db:aug": [
    { frets: [9, 8, 7, 6, 6, null], fingers: [4, 3, 2, 1, 1, 0], barres: [6] },
    {
      frets: [9, null, 11, 10, 10, 9],
      fingers: [1, 0, 4, 2, 3, 1],
      barres: [9],
    },
  ],
  "Db:6": [
    {
      frets: [null, 4, 3, 3, 2, null],
      fingers: [0, 4, 2, 3, 1, 0],
      barres: [],
    },
    { frets: [null, 4, 6, 6, 6, 6], fingers: [0, 1, 3, 3, 3, 3], barres: [6] },
    { frets: [9, 8, 8, 6, 6, 6], fingers: [4, 2, 3, 1, 1, 1], barres: [6] },
    {
      frets: [9, null, 11, 10, 11, 9],
      fingers: [1, 0, 3, 2, 4, 1],
      barres: [9],
    },
  ],
  "Db:7": [
    {
      frets: [null, 4, 3, 4, 2, null],
      fingers: [0, 3, 2, 4, 1, 0],
      barres: [],
    },
    { frets: [null, 4, 6, 4, 6, 4], fingers: [0, 1, 3, 1, 4, 1], barres: [4] },
    { frets: [9, 8, 6, 6, 6, 7], fingers: [4, 3, 1, 1, 1, 2], barres: [6] },
    { frets: [9, 11, 9, 10, 9, 9], fingers: [1, 3, 1, 2, 1, 1], barres: [9] },
  ],
  "Db:maj7": [
    { frets: [null, 4, 3, 1, 1, 1], fingers: [0, 4, 3, 1, 1, 1], barres: [1] },
    { frets: [4, 4, 6, 5, 6, 4], fingers: [1, 1, 3, 2, 4, 1], barres: [4] },
    {
      frets: [null, null, null, 6, 6, 8],
      fingers: [0, 0, 0, 1, 1, 3],
      barres: [6],
    },
    {
      frets: [9, null, 10, 10, 9, null],
      fingers: [1, 0, 3, 4, 2, 0],
      barres: [],
    },
  ],
  "Db:m6": [
    { frets: [null, 4, 2, 3, 2, 4], fingers: [0, 3, 1, 2, 1, 4], barres: [2] },
    {
      frets: [null, null, 6, 6, 5, 6],
      fingers: [0, 0, 2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [9, null, 8, 9, 9, null],
      fingers: [2, 0, 1, 3, 4, 0],
      barres: [],
    },
    { frets: [9, 11, 11, 9, 11, 9], fingers: [1, 2, 3, 1, 4, 1], barres: [9] },
  ],
  "Db:m7": [
    {
      frets: [9, null, 9, 9, 9, null],
      fingers: [2, 0, 3, 3, 3, 0],
      barres: [9],
    },
    { frets: [null, 4, 6, 4, 5, 4], fingers: [0, 1, 3, 1, 2, 1], barres: [4] },
    {
      frets: [null, null, 6, 6, 5, 7],
      fingers: [0, 0, 2, 3, 1, 4],
      barres: [],
    },
    { frets: [9, 11, 9, 9, 9, 9], fingers: [1, 4, 1, 1, 1, 1], barres: [9] },
    {
      frets: [null, null, 11, 13, 12, 12],
      fingers: [0, 0, 1, 4, 2, 3],
      barres: [],
    },
  ],
  "Db:m7b5": [
    {
      frets: [null, 4, 5, 4, 5, null],
      fingers: [0, 1, 3, 2, 4, 0],
      barres: [],
    },
    {
      frets: [null, null, 5, 6, 5, 7],
      fingers: [0, 0, 1, 2, 1, 4],
      barres: [5],
    },
    {
      frets: [9, null, 9, 9, 8, null],
      fingers: [2, 0, 3, 4, 1, 0],
      barres: [],
    },
    {
      frets: [null, null, 11, 12, 12, 12],
      fingers: [0, 0, 1, 2, 2, 2],
      barres: [12],
    },
  ],
  "Db:add9": [
    { frets: [null, 4, 3, 1, 4, 1], fingers: [0, 3, 2, 1, 4, 1], barres: [1] },
    {
      frets: [null, 4, 3, null, 4, 4],
      fingers: [0, 2, 1, 0, 3, 4],
      barres: [],
    },
    {
      frets: [9, 8, null, 8, 9, null],
      fingers: [3, 1, 0, 2, 4, 0],
      barres: [],
    },
    {
      frets: [null, null, 11, 10, 9, 11],
      fingers: [0, 0, 3, 2, 1, 4],
      barres: [],
    },
  ],
  "D:major": [
    {
      frets: [null, null, 0, 2, 3, 2],
      fingers: [0, 0, 0, 1, 3, 2],
      barres: [],
    },
    { frets: [null, 5, 4, 2, 3, 2], fingers: [0, 4, 3, 1, 2, 1], barres: [2] },
    { frets: [null, 5, 7, 7, 7, 5], fingers: [0, 1, 2, 3, 4, 1], barres: [5] },
    {
      frets: [10, 12, 12, 11, 10, 10],
      fingers: [1, 3, 4, 2, 1, 1],
      barres: [10],
    },
  ],
  "D:minor": [
    {
      frets: [null, null, 0, 2, 3, 1],
      fingers: [0, 0, 0, 2, 3, 1],
      barres: [],
    },
    { frets: [5, 5, 7, 7, 6, 5], fingers: [1, 1, 3, 4, 2, 1], barres: [5] },
    {
      frets: [null, 8, 7, 7, 6, null],
      fingers: [0, 4, 2, 3, 1, 0],
      barres: [],
    },
    {
      frets: [10, 12, 12, 10, 10, 10],
      fingers: [1, 3, 4, 1, 1, 1],
      barres: [10],
    },
  ],
  "D:dim": [
    {
      frets: [null, null, 0, 1, null, 1],
      fingers: [0, 0, 0, 1, 0, 2],
      barres: [],
    },
    {
      frets: [null, 5, 3, null, 3, 4],
      fingers: [0, 4, 1, 0, 2, 3],
      barres: [],
    },
    {
      frets: [null, 5, 6, 7, 6, null],
      fingers: [0, 1, 2, 4, 3, 0],
      barres: [],
    },
    {
      frets: [10, 8, null, 10, 9, null],
      fingers: [3, 1, 0, 4, 2, 0],
      barres: [],
    },
  ],
  "D:dim7": [
    {
      frets: [null, null, 0, 1, 0, 1],
      fingers: [0, 0, 0, 2, 0, 3],
      barres: [],
    },
    { frets: [null, 5, 6, 4, 6, 4], fingers: [0, 2, 3, 1, 4, 1], barres: [4] },
    { frets: [null, 8, 0, 10, 9, 7], fingers: [0, 2, 0, 4, 3, 1], barres: [] },
    {
      frets: [10, 11, 12, 10, 12, 10],
      fingers: [1, 2, 3, 1, 4, 1],
      barres: [10],
    },
  ],
  "D:sus2": [
    {
      frets: [null, null, 0, 2, 3, 0],
      fingers: [0, 0, 0, 2, 3, 0],
      barres: [],
    },
    {
      frets: [null, null, 2, 2, 3, 5],
      fingers: [0, 0, 1, 1, 2, 4],
      barres: [2],
    },
    { frets: [5, 5, 7, 7, 5, 5], fingers: [1, 1, 3, 4, 1, 1], barres: [5] },
    {
      frets: [null, 7, 7, 7, 10, 10],
      fingers: [0, 1, 1, 1, 4, 4],
      barres: [7, 10],
    },
  ],
  "D:sus4": [
    {
      frets: [null, null, 0, 2, 3, 3],
      fingers: [0, 0, 0, 1, 2, 3],
      barres: [],
    },
    { frets: [null, 5, 0, 0, 3, 5], fingers: [0, 3, 0, 0, 1, 4], barres: [] },
    { frets: [5, 5, 7, 7, 8, 5], fingers: [1, 1, 2, 3, 4, 1], barres: [5] },
    {
      frets: [10, 12, 12, 12, 10, 10],
      fingers: [1, 2, 3, 4, 1, 1],
      barres: [10],
    },
  ],
  "D:aug": [
    {
      frets: [null, null, 0, 3, 3, 2],
      fingers: [0, 0, 0, 2, 3, 1],
      barres: [],
    },
    {
      frets: [null, 5, 4, 3, 3, null],
      fingers: [0, 3, 2, 1, 1, 0],
      barres: [3],
    },
    { frets: [10, 9, 8, 7, 7, null], fingers: [4, 3, 2, 1, 1, 0], barres: [7] },
    {
      frets: [10, null, 12, 11, 11, null],
      fingers: [1, 0, 4, 2, 3, 0],
      barres: [],
    },
  ],
  "D:6": [
    {
      frets: [null, null, 0, 2, 0, 2],
      fingers: [0, 0, 0, 2, 0, 3],
      barres: [],
    },
    {
      frets: [null, 5, 4, 4, 3, null],
      fingers: [0, 4, 2, 3, 1, 0],
      barres: [],
    },
    { frets: [null, 5, 7, 7, 7, 7], fingers: [0, 1, 3, 3, 3, 4], barres: [7] },
    { frets: [7, 9, 7, 7, 10, 7], fingers: [1, 3, 1, 1, 4, 1], barres: [7] },
  ],
  "D:7": [
    {
      frets: [null, null, 0, 2, 1, 2],
      fingers: [0, 0, 0, 2, 1, 3],
      barres: [],
    },
    {
      frets: [null, 5, 4, 5, 3, null],
      fingers: [0, 3, 2, 4, 1, 0],
      barres: [],
    },
    { frets: [5, 5, 7, 5, 7, 5], fingers: [1, 1, 3, 1, 4, 1], barres: [5] },
    {
      frets: [10, 12, 10, 11, 10, 10],
      fingers: [1, 3, 1, 2, 1, 1],
      barres: [10],
    },
  ],
  "D:maj7": [
    {
      frets: [null, null, 0, 2, 2, 2],
      fingers: [0, 0, 0, 1, 1, 1],
      barres: [2],
    },
    { frets: [null, 5, 4, 2, 2, 2], fingers: [0, 4, 3, 1, 1, 1], barres: [2] },
    { frets: [5, 5, 7, 6, 7, 5], fingers: [1, 1, 3, 2, 4, 1], barres: [5] },
    {
      frets: [null, null, 7, 7, 7, 9],
      fingers: [0, 0, 1, 1, 1, 4],
      barres: [7],
    },
  ],
  "D:m6": [
    {
      frets: [null, null, 0, 2, 0, 1],
      fingers: [0, 0, 0, 2, 0, 1],
      barres: [],
    },
    { frets: [null, 5, 3, 4, 3, 5], fingers: [0, 3, 1, 2, 1, 4], barres: [3] },
    {
      frets: [null, 5, 7, null, 6, 7],
      fingers: [0, 1, 3, 0, 2, 4],
      barres: [],
    },
    {
      frets: [10, null, 9, 10, 10, 10],
      fingers: [2, 0, 1, 3, 3, 3],
      barres: [10],
    },
  ],
  "D:m7": [
    {
      frets: [10, null, 10, 10, 10, null],
      fingers: [2, 0, 3, 3, 3, 0],
      barres: [10],
    },
    {
      frets: [null, null, 0, 2, 1, 1],
      fingers: [0, 0, 0, 2, 1, 1],
      barres: [1],
    },
    { frets: [null, 5, 7, 5, 6, 5], fingers: [0, 1, 3, 1, 2, 1], barres: [5] },
    {
      frets: [null, null, 7, 7, 6, 8],
      fingers: [0, 0, 2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [10, 12, 10, 10, 10, 10],
      fingers: [1, 3, 1, 1, 1, 1],
      barres: [10],
    },
  ],
  "D:m7b5": [
    {
      frets: [null, null, 0, 1, 1, 1],
      fingers: [0, 0, 0, 1, 1, 1],
      barres: [1],
    },
    { frets: [null, 5, 3, 5, 3, 4], fingers: [0, 3, 1, 4, 1, 2], barres: [3] },
    {
      frets: [null, 5, 6, 5, 6, null],
      fingers: [0, 1, 3, 2, 4, 0],
      barres: [],
    },
    { frets: [null, 8, 0, 10, 9, 8], fingers: [0, 1, 0, 4, 3, 2], barres: [] },
  ],
  "D:add9": [
    { frets: [null, 5, 4, 2, 5, 2], fingers: [0, 3, 2, 1, 4, 1], barres: [2] },
    { frets: [null, 5, 7, 7, 7, 0], fingers: [0, 1, 2, 3, 4, 0], barres: [] },
    {
      frets: [null, null, 0, 9, 7, 10],
      fingers: [0, 0, 0, 3, 1, 4],
      barres: [],
    },
    {
      frets: [null, null, 12, 11, 10, 12],
      fingers: [0, 0, 3, 2, 1, 4],
      barres: [],
    },
  ],
  "Eb:major": [
    {
      frets: [null, null, 1, 3, 4, 3],
      fingers: [0, 0, 1, 2, 4, 3],
      barres: [],
    },
    { frets: [null, 6, 5, 3, 4, 3], fingers: [0, 4, 3, 1, 2, 1], barres: [3] },
    { frets: [null, 6, 8, 8, 8, 6], fingers: [0, 1, 2, 3, 4, 1], barres: [6] },
    {
      frets: [null, null, 8, 8, 8, 11],
      fingers: [0, 0, 1, 1, 1, 4],
      barres: [8],
    },
  ],
  "Eb:minor": [
    {
      frets: [null, null, 1, 3, 4, 2],
      fingers: [0, 0, 1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [null, null, 4, 3, 4, 2],
      fingers: [0, 0, 3, 2, 4, 1],
      barres: [],
    },
    { frets: [6, 6, 8, 8, 7, 6], fingers: [1, 1, 3, 4, 2, 1], barres: [6] },
    {
      frets: [11, 13, 13, 11, 11, 11],
      fingers: [1, 3, 4, 1, 1, 1],
      barres: [11],
    },
  ],
  "Eb:dim": [
    {
      frets: [null, null, 1, 2, null, 2],
      fingers: [0, 0, 1, 2, 0, 3],
      barres: [],
    },
    {
      frets: [null, 6, 4, null, 4, 5],
      fingers: [0, 4, 1, 0, 2, 3],
      barres: [],
    },
    {
      frets: [null, 6, 7, 8, 7, null],
      fingers: [0, 1, 2, 4, 3, 0],
      barres: [],
    },
    {
      frets: [11, 9, null, 11, 10, null],
      fingers: [3, 1, 0, 4, 2, 0],
      barres: [],
    },
  ],
  "Eb:dim7": [
    {
      frets: [null, null, 1, 2, 1, 2],
      fingers: [0, 0, 1, 3, 2, 4],
      barres: [],
    },
    { frets: [null, 6, 7, 5, 7, 5], fingers: [0, 2, 3, 1, 4, 1], barres: [5] },
    {
      frets: [null, null, 7, 8, 7, 8],
      fingers: [0, 0, 1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [11, null, 10, 11, 10, null],
      fingers: [2, 0, 1, 3, 1, 0],
      barres: [10],
    },
  ],
  "Eb:sus2": [
    { frets: [1, 1, 1, 3, 4, 1], fingers: [1, 1, 1, 3, 4, 1], barres: [1] },
    { frets: [6, 6, 8, 8, 6, 6], fingers: [1, 1, 3, 4, 1, 1], barres: [6] },
    {
      frets: [11, 8, 8, 10, 11, null],
      fingers: [3, 1, 1, 2, 4, 0],
      barres: [8],
    },
    {
      frets: [11, 13, 13, null, 11, 13],
      fingers: [1, 2, 3, 0, 1, 4],
      barres: [11],
    },
  ],
  "Eb:sus4": [
    {
      frets: [null, null, 1, 3, 4, 4],
      fingers: [0, 0, 1, 2, 3, 4],
      barres: [],
    },
    { frets: [6, 6, 8, 8, 9, 6], fingers: [1, 1, 2, 3, 4, 1], barres: [6] },
    {
      frets: [null, null, 8, 8, 9, null],
      fingers: [0, 0, 1, 1, 2, 0],
      barres: [8],
    },
    {
      frets: [11, 13, 13, 13, 11, 11],
      fingers: [1, 2, 3, 4, 1, 1],
      barres: [11],
    },
  ],
  "Eb:aug": [
    {
      frets: [null, null, 5, 4, 4, 3],
      fingers: [0, 0, 4, 2, 3, 1],
      barres: [],
    },
    {
      frets: [null, 6, 5, 4, 4, null],
      fingers: [0, 3, 2, 1, 1, 0],
      barres: [4],
    },
    {
      frets: [11, 10, 9, 8, 8, null],
      fingers: [4, 3, 2, 1, 1, 0],
      barres: [8],
    },
    {
      frets: [11, null, 13, 12, 12, null],
      fingers: [1, 0, 4, 2, 3, 0],
      barres: [],
    },
  ],
  "Eb:6": [
    {
      frets: [null, null, 1, 3, 1, 3],
      fingers: [0, 0, 1, 3, 1, 4],
      barres: [1],
    },
    {
      frets: [null, 6, 5, 5, 4, null],
      fingers: [0, 4, 2, 3, 1, 0],
      barres: [],
    },
    { frets: [null, 6, 8, 8, 8, 8], fingers: [0, 1, 3, 3, 3, 3], barres: [8] },
    {
      frets: [11, null, 10, 12, 11, null],
      fingers: [2, 0, 1, 4, 3, 0],
      barres: [],
    },
  ],
  "Eb:7": [
    {
      frets: [null, null, 1, 3, 2, 3],
      fingers: [0, 0, 1, 3, 2, 4],
      barres: [],
    },
    { frets: [null, 6, 8, 6, 8, 6], fingers: [0, 1, 3, 1, 4, 1], barres: [6] },
    {
      frets: [null, null, 8, 8, 8, 9],
      fingers: [0, 0, 1, 1, 1, 2],
      barres: [8],
    },
    {
      frets: [11, 13, 11, 12, 11, 11],
      fingers: [1, 3, 1, 2, 1, 1],
      barres: [11],
    },
  ],
  "Eb:maj7": [
    {
      frets: [null, 1, 1, 3, 3, 3],
      fingers: [0, 1, 1, 3, 3, 3],
      barres: [1, 3],
    },
    { frets: [null, 6, 5, 3, 3, 3], fingers: [0, 4, 3, 1, 1, 1], barres: [3] },
    { frets: [6, 6, 8, 7, 8, 6], fingers: [1, 1, 3, 2, 4, 1], barres: [6] },
    {
      frets: [null, null, 8, 8, 8, 10],
      fingers: [0, 0, 1, 1, 1, 4],
      barres: [8],
    },
  ],
  "Eb:m6": [
    { frets: [null, 1, 1, 3, 1, 2], fingers: [0, 1, 1, 3, 1, 2], barres: [1] },
    { frets: [null, 6, 4, 5, 4, 6], fingers: [0, 3, 1, 2, 1, 4], barres: [4] },
    {
      frets: [null, null, 8, 8, 7, 8],
      fingers: [0, 0, 2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [11, 13, 13, 11, 13, 11],
      fingers: [1, 2, 3, 1, 4, 1],
      barres: [11],
    },
  ],
  "Eb:m7": [
    {
      frets: [11, null, 11, 11, 11, null],
      fingers: [2, 0, 3, 3, 3, 0],
      barres: [11],
    },
    {
      frets: [null, null, 1, 3, 2, 2],
      fingers: [0, 0, 1, 4, 2, 3],
      barres: [],
    },
    { frets: [6, 6, 8, 6, 7, 6], fingers: [1, 1, 3, 1, 2, 1], barres: [6] },
    {
      frets: [null, null, 8, 8, 7, 9],
      fingers: [0, 0, 2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [11, 13, 11, 11, 11, 11],
      fingers: [1, 4, 1, 1, 1, 1],
      barres: [11],
    },
  ],
  "Eb:m7b5": [
    {
      frets: [null, null, 1, 2, 2, 2],
      fingers: [0, 0, 1, 2, 2, 2],
      barres: [2],
    },
    {
      frets: [null, 6, 7, 6, 7, null],
      fingers: [0, 1, 3, 2, 4, 0],
      barres: [],
    },
    {
      frets: [null, null, 7, 8, 7, 9],
      fingers: [0, 0, 1, 2, 1, 4],
      barres: [7],
    },
    {
      frets: [11, null, 11, 11, 10, null],
      fingers: [2, 0, 3, 4, 1, 0],
      barres: [],
    },
  ],
  "Eb:add9": [
    { frets: [null, 6, 5, 3, 6, 3], fingers: [0, 3, 2, 1, 4, 1], barres: [3] },
    { frets: [null, 6, 5, 0, 6, 6], fingers: [0, 2, 1, 0, 3, 4], barres: [] },
    {
      frets: [11, 10, null, 10, 11, null],
      fingers: [3, 1, 0, 2, 4, 0],
      barres: [],
    },
    {
      frets: [null, null, 13, 12, 11, 13],
      fingers: [0, 0, 3, 2, 1, 4],
      barres: [],
    },
  ],
  "E:major": [
    { frets: [0, 2, 2, 1, 0, 0], fingers: [0, 2, 3, 1, 0, 0], barres: [] },
    {
      frets: [null, null, 2, 4, 5, 4],
      fingers: [0, 0, 1, 2, 4, 3],
      barres: [],
    },
    { frets: [null, 7, 6, 4, 5, 4], fingers: [0, 4, 3, 1, 2, 1], barres: [4] },
    { frets: [null, 7, 9, 9, 9, 7], fingers: [0, 1, 2, 3, 4, 1], barres: [7] },
  ],
  "E:minor": [
    { frets: [0, 2, 2, 0, 0, 0], fingers: [0, 2, 3, 0, 0, 0], barres: [] },
    { frets: [0, 2, 2, 4, 5, 3], fingers: [0, 1, 1, 3, 4, 2], barres: [2] },
    { frets: [null, 7, 9, 9, 8, 7], fingers: [0, 1, 3, 4, 2, 1], barres: [7] },
    {
      frets: [12, 10, 9, 9, null, null],
      fingers: [4, 3, 1, 2, 0, 0],
      barres: [],
    },
  ],
  "E:dim": [
    {
      frets: [null, null, 2, 3, null, 3],
      fingers: [0, 0, 1, 2, 0, 3],
      barres: [],
    },
    {
      frets: [null, 7, 5, null, 5, 6],
      fingers: [0, 4, 1, 0, 2, 3],
      barres: [],
    },
    {
      frets: [null, 7, 8, 9, 8, null],
      fingers: [0, 1, 2, 4, 3, 0],
      barres: [],
    },
    {
      frets: [12, 10, null, 12, 11, null],
      fingers: [3, 1, 0, 4, 2, 0],
      barres: [],
    },
  ],
  "E:dim7": [
    { frets: [0, 1, 2, 0, 2, 0], fingers: [0, 1, 2, 0, 3, 0], barres: [] },
    {
      frets: [null, null, 2, 3, 2, 3],
      fingers: [0, 0, 1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [null, 7, 8, 6, 8, null],
      fingers: [0, 2, 3, 1, 4, 0],
      barres: [],
    },
    {
      frets: [12, null, 11, 12, 11, null],
      fingers: [2, 0, 1, 3, 1, 0],
      barres: [11],
    },
  ],
  "E:sus2": [
    { frets: [2, 2, 2, 4, 5, 2], fingers: [1, 1, 1, 3, 4, 1], barres: [2] },
    { frets: [0, 7, 9, 9, 7, 7], fingers: [0, 1, 3, 4, 1, 1], barres: [7] },
    { frets: [0, 9, 9, 9, 0, 0], fingers: [0, 1, 2, 3, 0, 0], barres: [] },
  ],
  "E:sus4": [
    { frets: [0, 2, 2, 2, 0, 0], fingers: [0, 2, 3, 4, 0, 0], barres: [] },
    { frets: [0, 2, 2, 4, 5, 5], fingers: [0, 1, 1, 2, 3, 4], barres: [2] },
    { frets: [7, 7, 9, 9, 10, 7], fingers: [1, 1, 2, 3, 4, 1], barres: [7] },
    {
      frets: [null, null, 9, 9, 10, 0],
      fingers: [0, 0, 1, 1, 2, 0],
      barres: [9],
    },
  ],
  "E:aug": [
    { frets: [0, 3, 2, 1, 1, 0], fingers: [0, 4, 3, 1, 2, 0], barres: [] },
    {
      frets: [null, 7, 6, 5, 5, null],
      fingers: [0, 3, 2, 1, 1, 0],
      barres: [5],
    },
    {
      frets: [null, 7, 10, 9, 9, null],
      fingers: [0, 3, 2, 1, 1, 0],
      barres: [9],
    },
    { frets: [12, 11, 10, 9, 9, 0], fingers: [4, 3, 2, 1, 1, 0], barres: [9] },
  ],
  "E:6": [
    { frets: [0, 2, 2, 1, 2, 0], fingers: [0, 2, 3, 1, 4, 0], barres: [] },
    { frets: [0, 2, 2, 4, 2, 4], fingers: [0, 1, 1, 3, 1, 4], barres: [2] },
    {
      frets: [null, 7, 6, 6, 5, null],
      fingers: [0, 4, 2, 3, 1, 0],
      barres: [],
    },
    { frets: [null, 7, 9, 9, 9, 9], fingers: [0, 1, 3, 3, 3, 3], barres: [9] },
  ],
  "E:7": [
    { frets: [0, 2, 0, 1, 0, 0], fingers: [0, 2, 0, 1, 0, 0], barres: [] },
    {
      frets: [null, 7, 6, 7, 5, null],
      fingers: [0, 3, 2, 4, 1, 0],
      barres: [],
    },
    { frets: [7, 7, 9, 7, 9, 7], fingers: [1, 1, 3, 1, 4, 1], barres: [7] },
    {
      frets: [null, null, 9, 9, 9, 10],
      fingers: [0, 0, 1, 1, 1, 2],
      barres: [9],
    },
  ],
  "E:maj7": [
    { frets: [0, 2, 1, 1, 0, 0], fingers: [0, 3, 1, 2, 0, 0], barres: [] },
    {
      frets: [null, null, 2, 4, 4, 4],
      fingers: [0, 0, 1, 3, 3, 3],
      barres: [4],
    },
    { frets: [null, 7, 6, 4, 4, 4], fingers: [0, 4, 3, 1, 1, 1], barres: [4] },
    { frets: [7, 7, 9, 8, 9, 7], fingers: [1, 1, 3, 2, 4, 1], barres: [7] },
  ],
  "E:m6": [
    { frets: [0, 2, 2, 0, 2, 0], fingers: [0, 1, 2, 0, 3, 0], barres: [] },
    { frets: [0, 2, 2, 4, 2, 3], fingers: [0, 1, 1, 3, 1, 2], barres: [2] },
    { frets: [null, 7, 5, 6, 5, 7], fingers: [0, 3, 1, 2, 1, 4], barres: [5] },
    {
      frets: [null, null, 9, 9, 8, 9],
      fingers: [0, 0, 2, 3, 1, 4],
      barres: [],
    },
  ],
  "E:m7": [
    {
      frets: [0, null, 0, 0, 0, null],
      fingers: [0, 0, 0, 0, 0, 0],
      barres: [],
    },
    {
      frets: [12, null, 12, 12, 12, null],
      fingers: [2, 0, 3, 3, 3, 0],
      barres: [12],
    },
    { frets: [0, 2, 2, 0, 3, 0], fingers: [0, 2, 3, 0, 4, 0], barres: [] },
    { frets: [0, 2, 0, 0, 0, 0], fingers: [0, 2, 0, 0, 0, 0], barres: [] },
    { frets: [0, 2, 2, 4, 3, 3], fingers: [0, 1, 1, 4, 2, 3], barres: [2] },
    { frets: [7, 7, 9, 7, 8, 7], fingers: [1, 1, 3, 1, 2, 1], barres: [7] },
    {
      frets: [null, null, 9, 9, 8, 10],
      fingers: [0, 0, 2, 3, 1, 4],
      barres: [],
    },
  ],
  "E:m7b5": [
    { frets: [0, 1, 2, 3, 3, 3], fingers: [0, 1, 2, 3, 3, 3], barres: [3] },
    {
      frets: [null, 7, 8, 7, 8, null],
      fingers: [0, 1, 3, 2, 4, 0],
      barres: [],
    },
    {
      frets: [null, null, 8, 9, 8, 10],
      fingers: [0, 0, 1, 2, 1, 4],
      barres: [8],
    },
    {
      frets: [12, null, 12, 12, 11, null],
      fingers: [2, 0, 3, 4, 1, 0],
      barres: [],
    },
  ],
  "E:add9": [
    { frets: [0, 2, 2, 1, 0, 2], fingers: [0, 2, 3, 1, 0, 4], barres: [] },
    { frets: [null, 7, 6, 4, 7, 4], fingers: [0, 3, 2, 1, 4, 1], barres: [4] },
    {
      frets: [null, 7, 6, null, 7, 7],
      fingers: [0, 2, 1, 0, 3, 4],
      barres: [],
    },
    {
      frets: [null, null, 14, 13, 12, 14],
      fingers: [0, 0, 3, 2, 1, 4],
      barres: [],
    },
  ],
  "F:major": [
    { frets: [1, 3, 3, 2, 1, 1], fingers: [1, 3, 4, 2, 1, 1], barres: [1] },
    {
      frets: [null, null, 3, 2, 1, 1],
      fingers: [0, 0, 3, 2, 1, 1],
      barres: [1],
    },
    {
      frets: [null, null, 3, 5, 6, 5],
      fingers: [0, 0, 1, 2, 4, 3],
      barres: [],
    },
    { frets: [null, 8, 7, 5, 6, 5], fingers: [0, 4, 3, 1, 2, 1], barres: [5] },
    {
      frets: [null, 8, 10, 10, 10, 8],
      fingers: [0, 1, 2, 3, 4, 1],
      barres: [8],
    },
  ],
  "F:minor": [
    { frets: [1, 3, 3, 1, 1, 1], fingers: [1, 3, 4, 1, 1, 1], barres: [1] },
    {
      frets: [null, null, 3, 5, 6, 4],
      fingers: [0, 0, 1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [null, 8, 10, 10, 9, 8],
      fingers: [0, 1, 3, 4, 2, 1],
      barres: [8],
    },
    {
      frets: [13, 11, 10, 10, null, null],
      fingers: [4, 2, 1, 1, 0, 0],
      barres: [10],
    },
  ],
  "F:dim": [
    {
      frets: [null, null, 3, 4, null, 4],
      fingers: [0, 0, 1, 2, 0, 3],
      barres: [],
    },
    {
      frets: [null, 8, 6, null, 6, 7],
      fingers: [0, 4, 1, 0, 2, 3],
      barres: [],
    },
    {
      frets: [null, 8, 9, 10, 9, null],
      fingers: [0, 1, 2, 4, 3, 0],
      barres: [],
    },
    {
      frets: [13, 11, null, 13, 12, null],
      fingers: [3, 1, 0, 4, 2, 0],
      barres: [],
    },
  ],
  "F:dim7": [
    { frets: [1, null, 0, 1, 0, 1], fingers: [1, 0, 0, 2, 0, 3], barres: [] },
    {
      frets: [null, null, 3, 4, 3, 4],
      fingers: [0, 0, 1, 3, 1, 4],
      barres: [3],
    },
    { frets: [7, 8, 9, 7, 9, 7], fingers: [1, 2, 3, 1, 4, 1], barres: [7] },
    {
      frets: [13, null, 12, 13, 12, null],
      fingers: [3, 0, 1, 4, 2, 0],
      barres: [],
    },
  ],
  "F:sus2": [
    { frets: [1, 3, 3, null, 1, 3], fingers: [1, 2, 3, 0, 1, 4], barres: [1] },
    { frets: [3, 3, 3, 5, 6, 3], fingers: [1, 1, 1, 3, 4, 1], barres: [3] },
    { frets: [8, 8, 10, 10, 8, 8], fingers: [1, 1, 3, 4, 1, 1], barres: [8] },
    {
      frets: [13, 10, 10, 12, 13, null],
      fingers: [3, 1, 1, 2, 4, 0],
      barres: [10],
    },
  ],
  "F:sus4": [
    { frets: [1, 3, 3, 3, 1, 1], fingers: [1, 2, 3, 4, 1, 1], barres: [1] },
    {
      frets: [null, null, 3, 5, 6, 6],
      fingers: [0, 0, 1, 2, 3, 4],
      barres: [],
    },
    { frets: [8, 8, 10, 10, 11, 8], fingers: [1, 1, 2, 3, 4, 1], barres: [8] },
    {
      frets: [null, null, 10, 10, 11, null],
      fingers: [0, 0, 1, 1, 2, 0],
      barres: [10],
    },
  ],
  "F:aug": [
    {
      frets: [null, null, 3, 2, 2, 1],
      fingers: [0, 0, 4, 2, 3, 1],
      barres: [],
    },
    {
      frets: [null, 8, 7, 6, 6, null],
      fingers: [0, 3, 2, 1, 1, 0],
      barres: [6],
    },
    {
      frets: [null, 8, null, 10, 10, 9],
      fingers: [0, 1, 0, 3, 4, 2],
      barres: [],
    },
    {
      frets: [13, 12, 11, 10, 10, null],
      fingers: [4, 3, 2, 1, 1, 0],
      barres: [10],
    },
  ],
  "F:6": [
    { frets: [1, null, 3, 2, 3, 1], fingers: [1, 0, 3, 2, 4, 1], barres: [1] },
    { frets: [null, 3, 3, 5, 3, 5], fingers: [0, 1, 1, 3, 1, 4], barres: [3] },
    {
      frets: [null, 8, 7, 7, 6, null],
      fingers: [0, 4, 2, 3, 1, 0],
      barres: [],
    },
    {
      frets: [8, 8, 10, 10, 10, 10],
      fingers: [1, 1, 3, 3, 3, 3],
      barres: [8, 10],
    },
  ],
  "F:7": [
    { frets: [1, 3, 1, 2, 1, 1], fingers: [1, 3, 1, 2, 1, 1], barres: [1] },
    { frets: [null, 3, 3, 5, 4, 5], fingers: [0, 1, 1, 3, 2, 4], barres: [3] },
    { frets: [8, 8, 10, 8, 10, 8], fingers: [1, 1, 3, 1, 4, 1], barres: [8] },
    {
      frets: [null, null, 10, 10, 10, 11],
      fingers: [0, 0, 1, 1, 1, 2],
      barres: [10],
    },
  ],
  "F:maj7": [
    {
      frets: [null, null, 3, 2, 1, 0],
      fingers: [0, 0, 3, 2, 1, 0],
      barres: [],
    },
    { frets: [1, 3, 2, 2, 1, 1], fingers: [1, 4, 2, 3, 1, 1], barres: [1] },
    {
      frets: [null, 3, 3, 5, 5, 5],
      fingers: [0, 1, 1, 3, 3, 3],
      barres: [3, 5],
    },
    { frets: [8, 8, 10, 9, 10, 8], fingers: [1, 1, 3, 2, 4, 1], barres: [8] },
  ],
  "F:m6": [
    { frets: [1, null, 0, 1, 1, 1], fingers: [1, 0, 0, 2, 3, 4], barres: [] },
    {
      frets: [null, null, 3, 5, 3, 4],
      fingers: [0, 0, 1, 3, 1, 2],
      barres: [3],
    },
    { frets: [null, 8, 6, 7, 6, 8], fingers: [0, 3, 1, 2, 1, 4], barres: [6] },
    {
      frets: [null, null, 10, 10, 9, 10],
      fingers: [0, 0, 2, 3, 1, 4],
      barres: [],
    },
  ],
  "F:m7": [
    {
      frets: [1, null, 1, 1, 1, null],
      fingers: [2, 0, 3, 3, 3, 0],
      barres: [1],
    },
    {
      frets: [13, null, 13, 13, 13, null],
      fingers: [2, 0, 3, 3, 3, 0],
      barres: [13],
    },
    { frets: [1, 3, 1, 1, 1, 1], fingers: [1, 3, 1, 1, 1, 1], barres: [1] },
    {
      frets: [null, null, 3, 5, 4, 4],
      fingers: [0, 0, 1, 4, 2, 3],
      barres: [],
    },
    { frets: [8, 8, 10, 8, 9, 8], fingers: [1, 1, 3, 1, 2, 1], barres: [8] },
    {
      frets: [null, null, 10, 10, 9, 11],
      fingers: [0, 0, 2, 3, 1, 4],
      barres: [],
    },
  ],
  "F:m7b5": [
    {
      frets: [1, null, 1, 1, 0, null],
      fingers: [1, 0, 2, 3, 0, 0],
      barres: [],
    },
    {
      frets: [null, null, 3, 4, 4, 4],
      fingers: [0, 0, 1, 2, 2, 2],
      barres: [4],
    },
    {
      frets: [null, 8, 9, 8, 9, null],
      fingers: [0, 1, 3, 2, 4, 0],
      barres: [],
    },
    {
      frets: [13, 11, 13, 13, 0, null],
      fingers: [2, 1, 3, 4, 0, 0],
      barres: [],
    },
  ],
  "F:add9": [
    {
      frets: [null, null, 3, 2, 1, 3],
      fingers: [0, 0, 3, 2, 1, 4],
      barres: [],
    },
    {
      frets: [null, null, 3, 0, 6, 5],
      fingers: [0, 0, 1, 0, 4, 3],
      barres: [],
    },
    { frets: [null, 8, 7, 5, 8, 5], fingers: [0, 3, 2, 1, 4, 1], barres: [5] },
    { frets: [null, 8, 7, 0, 8, 8], fingers: [0, 2, 1, 0, 3, 4], barres: [] },
  ],
  "Gb:major": [
    { frets: [2, 4, 4, 3, 2, 2], fingers: [1, 3, 4, 2, 1, 1], barres: [2] },
    { frets: [null, 4, 4, 6, 7, 6], fingers: [0, 1, 1, 2, 4, 3], barres: [4] },
    { frets: [6, 9, 8, 6, 7, 6], fingers: [1, 4, 3, 1, 2, 1], barres: [6] },
    { frets: [9, 9, 11, 11, 11, 9], fingers: [1, 1, 2, 3, 4, 1], barres: [9] },
  ],
  "Gb:minor": [
    { frets: [2, 4, 4, 2, 2, 2], fingers: [1, 3, 4, 1, 1, 1], barres: [2] },
    { frets: [null, 4, 4, 6, 7, 5], fingers: [0, 1, 1, 3, 4, 2], barres: [4] },
    {
      frets: [null, null, 7, 6, 7, 5],
      fingers: [0, 0, 3, 2, 4, 1],
      barres: [],
    },
    { frets: [9, 9, 11, 11, 10, 9], fingers: [1, 1, 3, 4, 2, 1], barres: [9] },
  ],
  "Gb:dim": [
    {
      frets: [2, 0, null, 2, 1, null],
      fingers: [2, 0, 0, 3, 1, 0],
      barres: [],
    },
    {
      frets: [null, null, 4, 5, null, 5],
      fingers: [0, 0, 1, 2, 0, 3],
      barres: [],
    },
    {
      frets: [null, 9, 7, null, 7, 8],
      fingers: [0, 4, 1, 0, 2, 3],
      barres: [],
    },
    {
      frets: [null, 9, 10, 11, 10, null],
      fingers: [0, 1, 2, 4, 3, 0],
      barres: [],
    },
  ],
  "Gb:dim7": [
    {
      frets: [2, null, 1, 2, 1, null],
      fingers: [2, 0, 1, 3, 1, 0],
      barres: [1],
    },
    { frets: [2, 3, 4, 2, 4, 2], fingers: [1, 2, 3, 1, 4, 1], barres: [2] },
    {
      frets: [null, null, 4, 5, 4, 5],
      fingers: [0, 0, 1, 3, 2, 4],
      barres: [],
    },
    { frets: [8, 9, 10, 8, 10, 8], fingers: [1, 2, 3, 1, 4, 1], barres: [8] },
  ],
  "Gb:sus2": [
    {
      frets: [2, null, null, 1, 2, 2],
      fingers: [2, 0, 0, 1, 3, 4],
      barres: [],
    },
    { frets: [4, 4, 4, 6, 7, 4], fingers: [1, 1, 1, 3, 4, 1], barres: [4] },
    { frets: [9, 9, 11, 11, 9, 9], fingers: [1, 1, 3, 4, 1, 1], barres: [9] },
    {
      frets: [14, 11, 11, 13, 14, null],
      fingers: [3, 1, 1, 2, 4, 0],
      barres: [11],
    },
  ],
  "Gb:sus4": [
    { frets: [2, 4, 4, 4, 2, 2], fingers: [1, 2, 3, 4, 1, 1], barres: [2] },
    { frets: [null, 4, 4, 6, 7, 7], fingers: [0, 1, 1, 2, 3, 4], barres: [4] },
    { frets: [9, 9, 11, 11, 12, 9], fingers: [1, 1, 2, 3, 4, 1], barres: [9] },
    {
      frets: [null, null, 11, 11, 12, 14],
      fingers: [0, 0, 1, 1, 2, 4],
      barres: [11],
    },
  ],
  "Gb:aug": [
    {
      frets: [null, null, 4, 3, 3, 2],
      fingers: [0, 0, 4, 2, 3, 1],
      barres: [],
    },
    {
      frets: [null, null, 4, 3, 3, null],
      fingers: [0, 0, 2, 1, 1, 0],
      barres: [3],
    },
    {
      frets: [null, 9, 8, 7, 7, null],
      fingers: [0, 3, 2, 1, 1, 0],
      barres: [7],
    },
    {
      frets: [14, 13, 12, 11, 11, null],
      fingers: [4, 3, 2, 1, 1, 0],
      barres: [11],
    },
  ],
  "Gb:6": [
    {
      frets: [2, null, 1, 3, 2, null],
      fingers: [2, 0, 1, 4, 3, 0],
      barres: [],
    },
    { frets: [2, null, 4, 3, 4, 2], fingers: [1, 0, 3, 2, 4, 1], barres: [2] },
    { frets: [null, 4, 4, 6, 4, 6], fingers: [0, 1, 1, 3, 1, 4], barres: [4] },
    {
      frets: [null, 9, 11, 11, 11, 11],
      fingers: [0, 1, 3, 3, 3, 3],
      barres: [11],
    },
  ],
  "Gb:7": [
    { frets: [2, 4, 2, 3, 2, 2], fingers: [1, 3, 1, 2, 1, 1], barres: [2] },
    { frets: [null, 4, 4, 6, 5, 6], fingers: [0, 1, 1, 3, 2, 4], barres: [4] },
    {
      frets: [null, 9, 8, 9, 7, null],
      fingers: [0, 3, 2, 4, 1, 0],
      barres: [],
    },
    { frets: [9, 9, 11, 9, 11, 9], fingers: [1, 1, 3, 1, 4, 1], barres: [9] },
  ],
  "Gb:maj7": [
    { frets: [2, 4, 3, 3, 2, 2], fingers: [1, 4, 2, 3, 1, 1], barres: [2] },
    {
      frets: [null, 4, 4, 6, 6, 6],
      fingers: [0, 1, 1, 3, 3, 3],
      barres: [4, 6],
    },
    { frets: [null, 9, 8, 6, 6, 6], fingers: [0, 4, 3, 1, 1, 1], barres: [6] },
    { frets: [9, 9, 11, 10, 11, 9], fingers: [1, 1, 3, 2, 4, 1], barres: [9] },
  ],
  "Gb:m6": [
    { frets: [2, null, 1, 2, 2, 2], fingers: [2, 0, 1, 3, 3, 4], barres: [2] },
    { frets: [null, 4, 4, 6, 4, 5], fingers: [0, 1, 1, 3, 1, 2], barres: [4] },
    { frets: [null, 9, 7, 8, 7, 9], fingers: [0, 3, 1, 2, 1, 4], barres: [7] },
    {
      frets: [null, 9, 11, 8, 10, null],
      fingers: [0, 2, 4, 1, 3, 0],
      barres: [],
    },
  ],
  "Gb:m7": [
    {
      frets: [2, null, 2, 2, 2, null],
      fingers: [2, 0, 3, 3, 3, 0],
      barres: [2],
    },
    {
      frets: [14, null, 14, 14, 14, null],
      fingers: [2, 0, 3, 3, 3, 0],
      barres: [14],
    },
    { frets: [2, 4, 2, 2, 2, 2], fingers: [1, 3, 1, 1, 1, 1], barres: [2] },
    {
      frets: [null, null, 4, 6, 5, 5],
      fingers: [0, 0, 1, 4, 2, 3],
      barres: [],
    },
    { frets: [9, 9, 11, 9, 10, 9], fingers: [1, 1, 3, 1, 2, 1], barres: [9] },
    {
      frets: [null, null, 11, 11, 10, 12],
      fingers: [0, 0, 2, 3, 1, 4],
      barres: [],
    },
  ],
  "Gb:m7b5": [
    { frets: [2, 0, 2, 2, 1, 0], fingers: [2, 0, 3, 4, 1, 0], barres: [] },
    {
      frets: [null, null, 4, 5, 5, 5],
      fingers: [0, 0, 1, 2, 2, 2],
      barres: [5],
    },
    {
      frets: [null, 9, 10, 9, 10, null],
      fingers: [0, 1, 3, 2, 4, 0],
      barres: [],
    },
    {
      frets: [null, null, 10, 11, 10, 12],
      fingers: [0, 0, 1, 2, 1, 4],
      barres: [10],
    },
  ],
  "Gb:add9": [
    { frets: [2, 1, null, 1, 2, 2], fingers: [3, 1, 0, 2, 4, 4], barres: [2] },
    {
      frets: [null, null, 4, 3, 2, 4],
      fingers: [0, 0, 3, 2, 1, 4],
      barres: [],
    },
    { frets: [null, 9, 8, 6, 9, 6], fingers: [0, 3, 2, 1, 4, 1], barres: [6] },
    {
      frets: [null, 9, 8, null, 9, 9],
      fingers: [0, 2, 1, 0, 3, 4],
      barres: [],
    },
  ],
  "G:major": [
    { frets: [3, 2, 0, 0, 0, 3], fingers: [2, 1, 0, 0, 0, 3], barres: [] },
    { frets: [3, 5, 5, 4, 3, 3], fingers: [1, 3, 4, 2, 1, 1], barres: [3] },
    {
      frets: [null, null, 5, 7, 8, 7],
      fingers: [0, 0, 1, 2, 4, 3],
      barres: [],
    },
    { frets: [7, 10, 9, 7, 8, 7], fingers: [1, 4, 3, 1, 2, 1], barres: [7] },
  ],
  "G:minor": [
    { frets: [3, 1, 0, 0, 3, 3], fingers: [2, 1, 0, 0, 3, 4], barres: [] },
    { frets: [3, 5, 5, 3, 3, 3], fingers: [1, 3, 4, 1, 1, 1], barres: [3] },
    {
      frets: [null, null, 5, 7, 8, 6],
      fingers: [0, 0, 1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [10, 10, 12, 12, 11, 10],
      fingers: [1, 1, 3, 4, 2, 1],
      barres: [10],
    },
  ],
  "G:dim": [
    {
      frets: [3, 1, null, 3, 2, null],
      fingers: [3, 1, 0, 4, 2, 0],
      barres: [],
    },
    {
      frets: [null, null, 5, 6, null, 6],
      fingers: [0, 0, 1, 2, 0, 3],
      barres: [],
    },
    {
      frets: [null, 10, 11, 12, 11, null],
      fingers: [0, 1, 2, 4, 3, 0],
      barres: [],
    },
  ],
  "G:dim7": [
    { frets: [3, 1, null, 3, 2, 0], fingers: [3, 1, 0, 4, 2, 0], barres: [] },
    { frets: [3, null, 2, 3, 2, 0], fingers: [3, 0, 1, 4, 2, 0], barres: [] },
    { frets: [3, 4, 5, 3, 5, 3], fingers: [1, 2, 3, 1, 4, 1], barres: [3] },
    {
      frets: [null, null, 5, 6, 5, 6],
      fingers: [0, 0, 1, 3, 2, 4],
      barres: [],
    },
  ],
  "G:sus2": [
    { frets: [3, 0, 0, 0, 3, 3], fingers: [1, 0, 0, 0, 2, 3], barres: [] },
    { frets: [5, 5, 5, 7, 8, 5], fingers: [1, 1, 1, 3, 4, 1], barres: [5] },
    {
      frets: [null, 10, 7, 7, 8, 10],
      fingers: [0, 3, 1, 1, 2, 4],
      barres: [7],
    },
    {
      frets: [10, 10, 12, 12, 10, 10],
      fingers: [1, 1, 3, 4, 1, 1],
      barres: [10],
    },
  ],
  "G:sus4": [
    { frets: [3, 3, 0, 0, 1, 3], fingers: [2, 3, 0, 0, 1, 4], barres: [] },
    { frets: [3, 5, 5, 5, 3, 3], fingers: [1, 2, 3, 4, 1, 1], barres: [3] },
    {
      frets: [null, 5, 5, 7, 8, 8],
      fingers: [0, 1, 1, 3, 4, 4],
      barres: [5, 8],
    },
    {
      frets: [10, 10, 12, 12, 13, 10],
      fingers: [1, 1, 2, 3, 4, 1],
      barres: [10],
    },
  ],
  "G:aug": [
    { frets: [3, 2, 1, 0, 0, null], fingers: [3, 2, 1, 0, 0, 0], barres: [] },
    {
      frets: [3, null, 5, 4, 4, null],
      fingers: [1, 0, 4, 2, 3, 0],
      barres: [],
    },
    {
      frets: [null, null, 5, 4, 4, null],
      fingers: [0, 0, 2, 1, 1, 0],
      barres: [4],
    },
    {
      frets: [null, 10, 9, 8, 8, null],
      fingers: [0, 3, 2, 1, 1, 0],
      barres: [8],
    },
  ],
  "G:6": [
    { frets: [3, 2, 0, 0, 0, 0], fingers: [2, 1, 0, 0, 0, 0], barres: [] },
    {
      frets: [3, null, 2, 4, 3, null],
      fingers: [2, 0, 1, 4, 3, 0],
      barres: [],
    },
    { frets: [null, 5, 5, 7, 5, 7], fingers: [0, 1, 1, 3, 1, 4], barres: [5] },
    {
      frets: [null, 10, 12, 12, 12, 12],
      fingers: [0, 1, 3, 3, 3, 4],
      barres: [12],
    },
  ],
  "G:7": [
    { frets: [3, 2, 0, 0, 0, 1], fingers: [3, 2, 0, 0, 0, 1], barres: [] },
    { frets: [3, 5, 3, 4, 3, 3], fingers: [1, 3, 1, 2, 1, 1], barres: [3] },
    { frets: [null, 5, 5, 7, 6, 7], fingers: [0, 1, 1, 3, 2, 4], barres: [5] },
    {
      frets: [10, 10, 12, 10, 12, 10],
      fingers: [1, 1, 3, 1, 4, 1],
      barres: [10],
    },
  ],
  "G:maj7": [
    { frets: [3, 2, 0, 0, 0, 2], fingers: [3, 2, 0, 0, 0, 1], barres: [] },
    { frets: [3, 5, 4, 4, 3, 3], fingers: [1, 4, 2, 3, 1, 1], barres: [3] },
    {
      frets: [null, 5, 5, 7, 7, 7],
      fingers: [0, 1, 1, 3, 3, 3],
      barres: [5, 7],
    },
    {
      frets: [null, 10, 12, 11, 12, 10],
      fingers: [0, 1, 3, 2, 4, 1],
      barres: [10],
    },
  ],
  "G:m6": [
    { frets: [3, null, 2, 3, 3, 3], fingers: [2, 0, 1, 3, 4, 4], barres: [3] },
    { frets: [3, 5, 5, 3, 5, 3], fingers: [1, 2, 3, 1, 4, 1], barres: [3] },
    { frets: [null, 5, 5, 7, 5, 6], fingers: [0, 1, 1, 3, 1, 2], barres: [5] },
    {
      frets: [null, 10, 8, 9, 8, 10],
      fingers: [0, 3, 1, 2, 1, 4],
      barres: [8],
    },
  ],
  "G:m7": [
    {
      frets: [3, null, 3, 3, 3, null],
      fingers: [2, 0, 3, 3, 3, 0],
      barres: [3],
    },
    { frets: [3, 5, 3, 3, 3, 3], fingers: [1, 3, 1, 1, 1, 1], barres: [3] },
    { frets: [null, 5, 5, 7, 6, 6], fingers: [0, 1, 1, 4, 2, 3], barres: [5] },
    {
      frets: [null, 10, 8, 10, 8, 10],
      fingers: [0, 2, 1, 3, 1, 4],
      barres: [8],
    },
    {
      frets: [10, 10, 12, 10, 11, 10],
      fingers: [1, 1, 3, 1, 2, 1],
      barres: [10],
    },
  ],
  "G:m7b5": [
    {
      frets: [3, null, null, 3, 2, 1],
      fingers: [3, 0, 0, 4, 2, 1],
      barres: [],
    },
    {
      frets: [3, null, 3, 3, 2, null],
      fingers: [2, 0, 3, 4, 1, 0],
      barres: [],
    },
    {
      frets: [null, null, 5, 6, 6, 6],
      fingers: [0, 0, 1, 2, 2, 2],
      barres: [6],
    },
    {
      frets: [null, 10, 11, 10, 11, null],
      fingers: [0, 1, 3, 2, 4, 0],
      barres: [],
    },
  ],
  "G:add9": [
    { frets: [3, 0, 0, 2, 0, 3], fingers: [2, 0, 0, 1, 0, 3], barres: [] },
    {
      frets: [null, 10, 9, 7, 10, 7],
      fingers: [0, 3, 2, 1, 4, 1],
      barres: [7],
    },
    {
      frets: [null, 10, 9, 0, 10, 10],
      fingers: [0, 2, 1, 0, 3, 4],
      barres: [],
    },
  ],
  "Ab:major": [
    { frets: [4, 3, 1, 1, 1, null], fingers: [3, 2, 1, 1, 1, 0], barres: [1] },
    { frets: [4, 6, 6, 5, 4, 4], fingers: [1, 3, 4, 2, 1, 1], barres: [4] },
    { frets: [null, 6, 6, 8, 9, 8], fingers: [0, 1, 1, 2, 4, 3], barres: [6] },
    { frets: [8, 11, 10, 8, 9, 8], fingers: [1, 4, 3, 1, 2, 1], barres: [8] },
  ],
  "Ab:minor": [
    { frets: [4, 6, 6, 4, 4, 4], fingers: [1, 3, 4, 1, 1, 1], barres: [4] },
    {
      frets: [null, null, 6, 8, 9, 7],
      fingers: [0, 0, 1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [null, null, 9, 8, 9, 7],
      fingers: [0, 0, 3, 2, 4, 1],
      barres: [],
    },
    {
      frets: [11, 11, 13, 13, 12, 11],
      fingers: [1, 1, 3, 4, 2, 1],
      barres: [11],
    },
  ],
  "Ab:dim": [
    {
      frets: [4, 2, null, 4, 3, null],
      fingers: [3, 1, 0, 4, 2, 0],
      barres: [],
    },
    {
      frets: [null, null, 6, 7, null, 7],
      fingers: [0, 0, 1, 2, 0, 3],
      barres: [],
    },
    {
      frets: [null, 11, 9, null, 9, 10],
      fingers: [0, 4, 1, 0, 2, 3],
      barres: [],
    },
    {
      frets: [null, 11, 12, 13, 12, null],
      fingers: [0, 1, 2, 4, 3, 0],
      barres: [],
    },
  ],
  "Ab:dim7": [
    {
      frets: [null, null, 0, 1, 0, 1],
      fingers: [0, 0, 0, 1, 0, 2],
      barres: [],
    },
    { frets: [4, null, 3, 4, 3, 4], fingers: [2, 0, 1, 3, 1, 4], barres: [3] },
    {
      frets: [null, null, 6, 7, 6, 7],
      fingers: [0, 0, 1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [10, 11, 12, 10, 12, 10],
      fingers: [1, 2, 3, 1, 4, 1],
      barres: [10],
    },
  ],
  "Ab:sus2": [
    {
      frets: [4, null, null, 3, 4, 4],
      fingers: [2, 0, 0, 1, 3, 4],
      barres: [],
    },
    { frets: [4, 6, 6, null, 4, 6], fingers: [1, 2, 3, 0, 1, 4], barres: [4] },
    { frets: [6, 6, 6, 8, 9, 6], fingers: [1, 1, 1, 3, 4, 1], barres: [6] },
    {
      frets: [11, 11, 13, 13, 11, 11],
      fingers: [1, 1, 3, 4, 1, 1],
      barres: [11],
    },
  ],
  "Ab:sus4": [
    {
      frets: [null, null, 1, 1, 2, 4],
      fingers: [0, 0, 1, 1, 2, 4],
      barres: [1],
    },
    { frets: [4, 6, 6, 6, 4, 4], fingers: [1, 2, 3, 4, 1, 1], barres: [4] },
    { frets: [null, 6, 6, 8, 9, 9], fingers: [0, 1, 1, 2, 3, 4], barres: [6] },
    {
      frets: [11, 11, 13, 13, 14, 11],
      fingers: [1, 1, 2, 3, 4, 1],
      barres: [11],
    },
  ],
  "Ab:aug": [
    { frets: [4, 3, 2, 1, 1, null], fingers: [4, 3, 2, 1, 1, 0], barres: [1] },
    {
      frets: [4, null, 6, 5, 5, null],
      fingers: [1, 0, 4, 2, 3, 0],
      barres: [],
    },
    {
      frets: [null, null, 6, 5, 5, null],
      fingers: [0, 0, 2, 1, 1, 0],
      barres: [5],
    },
    {
      frets: [null, 11, 10, 9, 9, null],
      fingers: [0, 3, 2, 1, 1, 0],
      barres: [9],
    },
  ],
  "Ab:6": [
    { frets: [null, 3, 1, 1, 1, 1], fingers: [0, 3, 1, 1, 1, 1], barres: [1] },
    {
      frets: [4, null, 3, 5, 4, null],
      fingers: [2, 0, 1, 4, 3, 0],
      barres: [],
    },
    { frets: [null, 6, 6, 8, 6, 8], fingers: [0, 1, 1, 3, 1, 4], barres: [6] },
    {
      frets: [null, 11, 10, 10, 9, null],
      fingers: [0, 4, 2, 3, 1, 0],
      barres: [],
    },
  ],
  "Ab:7": [
    {
      frets: [null, null, 1, 1, 1, 2],
      fingers: [0, 0, 1, 1, 1, 2],
      barres: [1],
    },
    { frets: [4, 6, 4, 5, 4, 4], fingers: [1, 3, 1, 2, 1, 1], barres: [4] },
    { frets: [null, 6, 6, 8, 7, 8], fingers: [0, 1, 1, 3, 2, 4], barres: [6] },
    {
      frets: [11, 11, 13, 11, 13, 11],
      fingers: [1, 1, 3, 1, 4, 1],
      barres: [11],
    },
  ],
  "Ab:maj7": [
    { frets: [4, 6, 5, 5, 4, 4], fingers: [1, 4, 2, 3, 1, 1], barres: [4] },
    {
      frets: [null, 6, 6, 8, 8, 8],
      fingers: [0, 1, 1, 3, 3, 3],
      barres: [6, 8],
    },
    {
      frets: [null, 11, 10, 12, 9, null],
      fingers: [0, 3, 2, 4, 1, 0],
      barres: [],
    },
    {
      frets: [11, 11, 13, 12, 13, 11],
      fingers: [1, 1, 3, 2, 4, 1],
      barres: [11],
    },
  ],
  "Ab:m6": [
    {
      frets: [4, null, 3, 4, 4, null],
      fingers: [2, 0, 1, 3, 4, 0],
      barres: [],
    },
    { frets: [4, 6, 6, 4, 6, 4], fingers: [1, 2, 3, 1, 4, 1], barres: [4] },
    { frets: [null, 6, 6, 8, 6, 7], fingers: [0, 1, 1, 3, 1, 2], barres: [6] },
    {
      frets: [null, 11, 9, 10, 9, 11],
      fingers: [0, 3, 1, 2, 1, 4],
      barres: [9],
    },
  ],
  "Ab:m7": [
    {
      frets: [4, null, 4, 4, 4, null],
      fingers: [2, 0, 3, 3, 3, 0],
      barres: [4],
    },
    { frets: [4, 6, 4, 4, 4, 4], fingers: [1, 3, 1, 1, 1, 1], barres: [4] },
    { frets: [null, 6, 6, 8, 7, 7], fingers: [0, 1, 1, 4, 2, 3], barres: [6] },
    {
      frets: [null, 11, 9, 11, 9, null],
      fingers: [0, 2, 1, 3, 1, 0],
      barres: [9],
    },
    {
      frets: [11, 11, 13, 11, 12, 11],
      fingers: [1, 1, 3, 1, 2, 1],
      barres: [11],
    },
  ],
  "Ab:m7b5": [
    {
      frets: [null, null, 0, 1, 0, 2],
      fingers: [0, 0, 0, 1, 0, 3],
      barres: [],
    },
    {
      frets: [4, null, 4, 4, 3, null],
      fingers: [2, 0, 3, 4, 1, 0],
      barres: [],
    },
    {
      frets: [null, null, 6, 7, 7, 7],
      fingers: [0, 0, 1, 2, 2, 2],
      barres: [7],
    },
    {
      frets: [null, 11, 12, 11, 12, null],
      fingers: [0, 1, 3, 2, 4, 0],
      barres: [],
    },
  ],
  "Ab:add9": [
    {
      frets: [4, 3, null, 3, 4, null],
      fingers: [3, 1, 0, 2, 4, 0],
      barres: [],
    },
    {
      frets: [null, null, 6, 5, 4, 6],
      fingers: [0, 0, 3, 2, 1, 4],
      barres: [],
    },
    {
      frets: [null, 11, 10, 8, 11, 8],
      fingers: [0, 3, 2, 1, 4, 1],
      barres: [8],
    },
    {
      frets: [null, 11, 10, null, 11, 11],
      fingers: [0, 2, 1, 0, 3, 4],
      barres: [],
    },
  ],
  "A:major": [
    { frets: [null, 0, 2, 2, 2, 0], fingers: [0, 0, 1, 2, 3, 0], barres: [] },
    { frets: [null, 0, 2, 2, 2, 5], fingers: [0, 0, 1, 1, 1, 4], barres: [2] },
    { frets: [5, 7, 7, 6, 5, 5], fingers: [1, 3, 4, 2, 1, 1], barres: [5] },
    { frets: [null, 0, 7, 9, 10, 9], fingers: [0, 0, 1, 2, 4, 3], barres: [] },
  ],
  "A:minor": [
    { frets: [null, 0, 2, 2, 1, 0], fingers: [0, 0, 2, 3, 1, 0], barres: [] },
    { frets: [null, 0, 2, 5, 5, 5], fingers: [0, 0, 1, 4, 4, 4], barres: [5] },
    { frets: [5, 7, 7, 5, 5, 5], fingers: [1, 3, 4, 1, 1, 1], barres: [5] },
    { frets: [null, 0, 7, 9, 10, 8], fingers: [0, 0, 1, 3, 4, 2], barres: [] },
  ],
  "A:dim": [
    {
      frets: [null, 0, 1, 2, 1, null],
      fingers: [0, 0, 1, 3, 2, 0],
      barres: [],
    },
    {
      frets: [null, null, 7, 8, null, 8],
      fingers: [0, 0, 1, 2, 0, 3],
      barres: [],
    },
    {
      frets: [null, 12, 10, null, 10, 11],
      fingers: [0, 4, 1, 0, 2, 3],
      barres: [],
    },
  ],
  "A:dim7": [
    { frets: [null, 0, 1, 2, 1, 2], fingers: [0, 0, 1, 3, 2, 4], barres: [] },
    {
      frets: [5, null, 4, 5, 4, null],
      fingers: [2, 0, 1, 3, 1, 0],
      barres: [4],
    },
    { frets: [5, 6, 7, 5, 7, 5], fingers: [1, 2, 3, 1, 4, 1], barres: [5] },
    { frets: [null, 0, 7, 8, 7, 8], fingers: [0, 0, 1, 3, 2, 4], barres: [] },
  ],
  "A:sus2": [
    { frets: [null, 0, 2, 2, 0, 0], fingers: [0, 0, 2, 3, 0, 0], barres: [] },
    { frets: [null, 0, 2, 4, 0, 0], fingers: [0, 0, 1, 4, 0, 0], barres: [] },
    { frets: [7, 7, 7, 9, 10, 7], fingers: [1, 1, 1, 3, 4, 1], barres: [7] },
    { frets: [null, 0, 9, 9, 0, 0], fingers: [0, 0, 1, 2, 0, 0], barres: [] },
  ],
  "A:sus4": [
    { frets: [null, 0, 2, 2, 3, 0], fingers: [0, 0, 1, 2, 3, 0], barres: [] },
    {
      frets: [null, 0, 0, null, 3, 0],
      fingers: [0, 0, 0, 0, 1, 0],
      barres: [],
    },
    { frets: [5, 7, 7, 7, 5, 5], fingers: [1, 3, 3, 4, 1, 1], barres: [5, 7] },
    {
      frets: [null, 7, 7, 9, 10, 10],
      fingers: [0, 1, 1, 2, 3, 4],
      barres: [7],
    },
  ],
  "A:aug": [
    { frets: [null, 0, 3, 2, 2, 1], fingers: [0, 0, 4, 2, 3, 1], barres: [] },
    { frets: [5, 4, 3, 2, 2, null], fingers: [4, 3, 2, 1, 1, 0], barres: [2] },
    { frets: [5, null, 7, 6, 6, 5], fingers: [1, 0, 4, 2, 3, 1], barres: [5] },
    {
      frets: [null, 12, 11, 10, 10, null],
      fingers: [0, 3, 2, 1, 1, 0],
      barres: [10],
    },
  ],
  "A:6": [
    { frets: [null, 0, 2, 2, 2, 2], fingers: [0, 0, 1, 1, 1, 1], barres: [2] },
    {
      frets: [5, null, 4, 6, 5, null],
      fingers: [2, 0, 1, 4, 3, 0],
      barres: [],
    },
    { frets: [5, 7, null, 6, 7, 5], fingers: [1, 3, 0, 2, 4, 1], barres: [5] },
    {
      frets: [null, 12, 11, 11, 10, null],
      fingers: [0, 4, 2, 3, 1, 0],
      barres: [],
    },
  ],
  "A:7": [
    { frets: [null, 0, 2, 0, 2, 0], fingers: [0, 0, 2, 0, 3, 0], barres: [] },
    { frets: [null, 0, 2, 2, 2, 3], fingers: [0, 0, 1, 1, 1, 2], barres: [2] },
    { frets: [5, 7, 5, 6, 5, 5], fingers: [1, 3, 1, 2, 1, 1], barres: [5] },
    { frets: [null, 0, 7, 9, 8, 9], fingers: [0, 0, 1, 3, 2, 4], barres: [] },
  ],
  "A:maj7": [
    { frets: [null, 0, 2, 1, 2, 0], fingers: [0, 0, 2, 1, 3, 0], barres: [] },
    { frets: [null, 0, 2, 2, 2, 4], fingers: [0, 0, 1, 1, 1, 4], barres: [2] },
    { frets: [5, 7, 6, 6, 5, 5], fingers: [1, 4, 2, 3, 1, 1], barres: [5] },
    { frets: [null, 0, 7, 9, 9, 9], fingers: [0, 0, 1, 3, 3, 3], barres: [9] },
  ],
  "A:m6": [
    { frets: [null, 0, 2, 2, 1, 2], fingers: [0, 0, 2, 3, 1, 4], barres: [] },
    { frets: [5, null, 4, 5, 5, 5], fingers: [2, 0, 1, 3, 3, 4], barres: [5] },
    { frets: [5, 7, 7, 5, 7, 5], fingers: [1, 2, 3, 1, 4, 1], barres: [5] },
    { frets: [null, 7, 7, 9, 7, 8], fingers: [0, 1, 1, 3, 1, 2], barres: [7] },
  ],
  "A:m7": [
    { frets: [null, 0, 2, 0, 1, 0], fingers: [0, 0, 2, 0, 1, 0], barres: [] },
    { frets: [null, 0, 2, 2, 1, 3], fingers: [0, 0, 2, 3, 1, 4], barres: [] },
    {
      frets: [5, null, 5, 5, 5, null],
      fingers: [2, 0, 3, 3, 3, 0],
      barres: [5],
    },
    { frets: [null, 0, 5, 5, 5, 5], fingers: [0, 0, 1, 1, 1, 1], barres: [5] },
    { frets: [5, 7, 5, 5, 5, 5], fingers: [1, 3, 1, 1, 1, 1], barres: [5] },
    { frets: [null, 7, 7, 9, 8, 8], fingers: [0, 1, 1, 4, 2, 3], barres: [7] },
  ],
  "A:m7b5": [
    {
      frets: [null, 0, 1, 0, 1, null],
      fingers: [0, 0, 2, 0, 3, 0],
      barres: [],
    },
    {
      frets: [5, null, 5, 5, 4, null],
      fingers: [2, 0, 3, 4, 1, 0],
      barres: [],
    },
    { frets: [5, 6, 7, 5, 8, 5], fingers: [1, 2, 3, 1, 4, 1], barres: [5] },
    {
      frets: [null, null, 7, 8, 8, 8],
      fingers: [0, 0, 1, 2, 2, 2],
      barres: [8],
    },
  ],
  "A:add9": [
    { frets: [null, 0, 2, 4, 2, 0], fingers: [0, 0, 1, 3, 2, 0], barres: [] },
    {
      frets: [null, null, 7, 6, 5, 7],
      fingers: [0, 0, 3, 2, 1, 4],
      barres: [],
    },
    {
      frets: [null, 12, 11, 9, 12, 9],
      fingers: [0, 3, 2, 1, 4, 1],
      barres: [9],
    },
    {
      frets: [null, 12, 11, null, 12, 12],
      fingers: [0, 2, 1, 0, 3, 4],
      barres: [],
    },
  ],
  "Bb:major": [
    { frets: [null, 1, 3, 3, 3, 1], fingers: [0, 1, 2, 3, 4, 1], barres: [1] },
    { frets: [6, 5, 3, 3, 3, null], fingers: [4, 3, 1, 1, 1, 0], barres: [3] },
    { frets: [6, 8, 8, 7, 6, 6], fingers: [1, 3, 4, 2, 1, 1], barres: [6] },
    {
      frets: [null, 8, 8, 10, 11, 10],
      fingers: [0, 1, 1, 2, 4, 3],
      barres: [8],
    },
  ],
  "Bb:minor": [
    { frets: [null, 1, 3, 3, 2, 1], fingers: [0, 1, 3, 4, 2, 1], barres: [1] },
    { frets: [6, 8, 8, 6, 6, 6], fingers: [1, 3, 4, 1, 1, 1], barres: [6] },
    {
      frets: [null, null, 8, 6, 6, 6],
      fingers: [0, 0, 3, 1, 1, 1],
      barres: [6],
    },
    {
      frets: [null, null, 8, 10, 11, 9],
      fingers: [0, 0, 1, 3, 4, 2],
      barres: [],
    },
  ],
  "Bb:dim": [
    {
      frets: [null, 1, 2, 3, 2, null],
      fingers: [0, 1, 2, 4, 3, 0],
      barres: [],
    },
    {
      frets: [6, 4, null, 6, 5, null],
      fingers: [3, 1, 0, 4, 2, 0],
      barres: [],
    },
    {
      frets: [null, null, 8, 9, null, 9],
      fingers: [0, 0, 1, 2, 0, 3],
      barres: [],
    },
    {
      frets: [null, 13, 11, null, 11, 12],
      fingers: [0, 4, 1, 0, 2, 3],
      barres: [],
    },
  ],
  "Bb:dim7": [
    { frets: [null, 1, 2, 0, 2, 0], fingers: [0, 1, 2, 0, 3, 0], barres: [] },
    {
      frets: [null, null, 2, 3, 2, 3],
      fingers: [0, 0, 1, 3, 2, 4],
      barres: [],
    },
    { frets: [6, 7, 8, 6, 8, 6], fingers: [1, 2, 3, 1, 4, 1], barres: [6] },
    {
      frets: [null, null, 8, 9, 8, 9],
      fingers: [0, 0, 1, 3, 2, 4],
      barres: [],
    },
  ],
  "Bb:sus2": [
    { frets: [1, 1, 3, 3, 1, 1], fingers: [1, 1, 3, 4, 1, 1], barres: [1] },
    { frets: [6, 3, 3, 5, 6, null], fingers: [3, 1, 1, 2, 4, 0], barres: [3] },
    { frets: [8, 8, 8, 10, 11, 8], fingers: [1, 1, 1, 3, 4, 1], barres: [8] },
    {
      frets: [null, 13, 10, 10, 11, 13],
      fingers: [0, 3, 1, 1, 2, 4],
      barres: [10],
    },
  ],
  "Bb:sus4": [
    { frets: [null, 1, 3, 3, 4, 1], fingers: [0, 1, 2, 3, 4, 1], barres: [1] },
    {
      frets: [null, null, 3, 3, 4, 6],
      fingers: [0, 0, 1, 1, 2, 4],
      barres: [3],
    },
    { frets: [6, 8, 8, 8, 6, 6], fingers: [1, 3, 3, 3, 1, 1], barres: [6, 8] },
    {
      frets: [null, 8, 8, 10, 11, 11],
      fingers: [0, 1, 1, 2, 3, 4],
      barres: [8],
    },
  ],
  "Bb:aug": [
    {
      frets: [null, 1, 4, 3, 3, null],
      fingers: [0, 1, 4, 2, 3, 0],
      barres: [],
    },
    { frets: [6, 5, 4, 3, 3, null], fingers: [4, 3, 2, 1, 1, 0], barres: [3] },
    {
      frets: [null, null, 8, 7, 7, 6],
      fingers: [0, 0, 4, 2, 3, 1],
      barres: [],
    },
    {
      frets: [null, null, 8, 7, 7, null],
      fingers: [0, 0, 2, 1, 1, 0],
      barres: [7],
    },
  ],
  "Bb:6": [
    { frets: [null, 1, 3, 3, 3, 3], fingers: [0, 1, 3, 3, 3, 3], barres: [3] },
    { frets: [6, 5, 0, 0, 6, 6], fingers: [2, 1, 0, 0, 3, 4], barres: [] },
  ],
  "Bb:7": [
    { frets: [null, 1, 3, 1, 3, 1], fingers: [0, 1, 3, 1, 4, 1], barres: [1] },
    { frets: [6, 8, 6, 7, 6, 6], fingers: [1, 3, 1, 2, 1, 1], barres: [6] },
    {
      frets: [null, 8, 8, 10, 9, 10],
      fingers: [0, 1, 1, 3, 2, 4],
      barres: [8],
    },
    {
      frets: [null, 13, 12, 13, 11, null],
      fingers: [0, 3, 2, 4, 1, 0],
      barres: [],
    },
  ],
  "Bb:maj7": [
    { frets: [null, 1, 3, 2, 3, 1], fingers: [0, 1, 3, 2, 4, 1], barres: [1] },
    {
      frets: [null, null, 3, 3, 3, 5],
      fingers: [0, 0, 1, 1, 1, 4],
      barres: [3],
    },
    { frets: [6, 8, 7, 7, 6, 6], fingers: [1, 4, 2, 3, 1, 1], barres: [6] },
    {
      frets: [null, 8, 8, 10, 10, 10],
      fingers: [0, 1, 1, 3, 3, 3],
      barres: [8, 10],
    },
  ],
  "Bb:m6": [
    {
      frets: [null, 1, 3, null, 2, 3],
      fingers: [0, 1, 3, 0, 2, 4],
      barres: [],
    },
    {
      frets: [null, 4, 5, 3, 6, null],
      fingers: [0, 2, 3, 1, 4, 0],
      barres: [],
    },
    { frets: [6, null, 5, 6, 6, 6], fingers: [2, 0, 1, 3, 3, 4], barres: [6] },
    { frets: [6, 8, 8, 6, 8, 6], fingers: [1, 2, 3, 1, 4, 1], barres: [6] },
  ],
  "Bb:m7": [
    { frets: [null, 1, 3, 1, 2, 1], fingers: [0, 1, 3, 1, 2, 1], barres: [1] },
    {
      frets: [null, null, 3, 3, 2, 4],
      fingers: [0, 0, 2, 3, 1, 4],
      barres: [],
    },
    { frets: [6, 8, 6, 6, 6, 6], fingers: [1, 3, 1, 1, 1, 1], barres: [6] },
    { frets: [null, 8, 8, 10, 9, 9], fingers: [0, 1, 1, 4, 2, 3], barres: [8] },
  ],
  "Bb:m7b5": [
    {
      frets: [null, 1, 2, 1, 2, null],
      fingers: [0, 1, 3, 2, 4, 0],
      barres: [],
    },
    {
      frets: [null, null, 2, 3, 2, 4],
      fingers: [0, 0, 1, 2, 1, 4],
      barres: [2],
    },
    {
      frets: [6, null, 6, 6, 5, null],
      fingers: [2, 0, 3, 4, 1, 0],
      barres: [],
    },
    {
      frets: [null, null, 8, 9, 9, 9],
      fingers: [0, 0, 1, 2, 2, 2],
      barres: [9],
    },
  ],
  "Bb:add9": [
    { frets: [null, 1, 0, 3, 1, 1], fingers: [0, 1, 0, 4, 2, 3], barres: [] },
    {
      frets: [null, null, 8, 7, 6, 8],
      fingers: [0, 0, 3, 2, 1, 4],
      barres: [],
    },
    {
      frets: [null, null, 8, 7, null, 8],
      fingers: [0, 0, 2, 1, 0, 3],
      barres: [],
    },
    {
      frets: [null, 13, 12, 10, 13, 10],
      fingers: [0, 3, 2, 1, 4, 1],
      barres: [10],
    },
  ],
  "B:major": [
    { frets: [2, 2, 4, 4, 4, 2], fingers: [1, 1, 2, 3, 4, 1], barres: [2] },
    {
      frets: [null, null, 4, 4, 4, 7],
      fingers: [0, 0, 1, 1, 1, 4],
      barres: [4],
    },
    { frets: [7, 9, 9, 8, 7, 7], fingers: [1, 3, 4, 2, 1, 1], barres: [7] },
    {
      frets: [null, 9, 9, 11, 12, 11],
      fingers: [0, 1, 1, 2, 4, 3],
      barres: [9],
    },
  ],
  "B:minor": [
    { frets: [2, 2, 4, 4, 3, 2], fingers: [1, 1, 3, 4, 2, 1], barres: [2] },
    { frets: [7, 9, 9, 7, 7, 7], fingers: [1, 3, 4, 1, 1, 1], barres: [7] },
    {
      frets: [null, null, 9, 11, 12, 10],
      fingers: [0, 0, 1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [null, null, 12, 11, 12, 10],
      fingers: [0, 0, 3, 2, 4, 1],
      barres: [],
    },
  ],
  "B:dim": [
    {
      frets: [null, 2, 0, null, 0, 1],
      fingers: [0, 3, 0, 0, 0, 2],
      barres: [],
    },
    {
      frets: [null, 2, 3, 4, 3, null],
      fingers: [0, 1, 2, 4, 3, 0],
      barres: [],
    },
    {
      frets: [7, 5, null, 7, 6, null],
      fingers: [3, 1, 0, 4, 2, 0],
      barres: [],
    },
    {
      frets: [null, null, 9, 10, null, 10],
      fingers: [0, 0, 1, 2, 0, 3],
      barres: [],
    },
  ],
  "B:dim7": [
    { frets: [null, 2, 3, 1, 3, 1], fingers: [0, 2, 3, 1, 4, 1], barres: [1] },
    {
      frets: [null, null, 3, 4, 3, 4],
      fingers: [0, 0, 1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [7, null, 6, 7, 6, null],
      fingers: [3, 0, 1, 4, 2, 0],
      barres: [],
    },
    { frets: [7, 8, 9, 7, 9, 7], fingers: [1, 2, 3, 1, 4, 1], barres: [7] },
  ],
  "B:sus2": [
    { frets: [2, 2, 4, 4, 2, 2], fingers: [1, 1, 3, 4, 1, 1], barres: [2] },
    {
      frets: [7, null, null, 6, 7, 7],
      fingers: [2, 0, 0, 1, 3, 4],
      barres: [],
    },
    { frets: [9, 9, 9, 11, 12, 9], fingers: [1, 1, 1, 3, 4, 1], barres: [9] },
    {
      frets: [null, 14, 11, 11, 12, 14],
      fingers: [0, 3, 1, 1, 2, 4],
      barres: [11],
    },
  ],
  "B:sus4": [
    { frets: [2, 2, 4, 4, 5, 2], fingers: [1, 1, 2, 3, 4, 1], barres: [2] },
    {
      frets: [null, null, 4, 4, 5, 7],
      fingers: [0, 0, 1, 1, 2, 4],
      barres: [4],
    },
    { frets: [7, 9, 9, 9, 7, 7], fingers: [1, 2, 3, 4, 1, 1], barres: [7] },
    {
      frets: [null, 9, 9, 11, 12, 12],
      fingers: [0, 1, 1, 3, 4, 4],
      barres: [9, 12],
    },
  ],
  "B:aug": [
    {
      frets: [null, 2, 1, 0, 0, null],
      fingers: [0, 2, 1, 0, 0, 0],
      barres: [],
    },
    {
      frets: [null, null, 5, 4, 4, 3],
      fingers: [0, 0, 4, 2, 3, 1],
      barres: [],
    },
    {
      frets: [7, null, 9, 8, 8, null],
      fingers: [1, 0, 4, 2, 3, 0],
      barres: [],
    },
  ],
  "B:6": [
    {
      frets: [null, 2, 1, 1, 0, null],
      fingers: [0, 3, 1, 2, 0, 0],
      barres: [],
    },
    { frets: [null, 2, 4, 4, 4, 4], fingers: [0, 1, 3, 3, 3, 3], barres: [4] },
    {
      frets: [7, null, 9, 8, 9, null],
      fingers: [1, 0, 3, 2, 4, 0],
      barres: [],
    },
    {
      frets: [null, null, 9, 11, 9, 11],
      fingers: [0, 0, 1, 3, 1, 4],
      barres: [9],
    },
  ],
  "B:7": [
    { frets: [null, 2, 1, 2, 0, 2], fingers: [0, 2, 1, 3, 0, 4], barres: [] },
    { frets: [2, 2, 4, 2, 4, 2], fingers: [1, 1, 3, 1, 4, 1], barres: [2] },
    {
      frets: [null, null, 4, 4, 4, 5],
      fingers: [0, 0, 1, 1, 1, 2],
      barres: [4],
    },
    { frets: [7, 9, 7, 8, 7, 7], fingers: [1, 3, 1, 2, 1, 1], barres: [7] },
  ],
  "B:maj7": [
    { frets: [2, 2, 4, 3, 4, 2], fingers: [1, 1, 3, 2, 4, 1], barres: [2] },
    {
      frets: [null, null, 4, 4, 4, 6],
      fingers: [0, 0, 1, 1, 1, 4],
      barres: [4],
    },
    { frets: [7, 9, 8, 8, 7, 7], fingers: [1, 4, 2, 3, 1, 1], barres: [7] },
    {
      frets: [null, 9, 9, 11, 11, 11],
      fingers: [0, 1, 1, 3, 3, 3],
      barres: [9, 11],
    },
  ],
  "B:m6": [
    { frets: [2, 2, 0, 1, 0, 2], fingers: [2, 3, 0, 1, 0, 4], barres: [] },
    {
      frets: [null, null, 4, 4, 3, 4],
      fingers: [0, 0, 2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [7, null, 6, 7, 7, null],
      fingers: [2, 0, 1, 3, 4, 0],
      barres: [],
    },
    { frets: [7, 9, 9, 7, 9, 7], fingers: [1, 2, 3, 1, 4, 1], barres: [7] },
  ],
  "B:m7": [
    {
      frets: [7, null, 7, 7, 7, null],
      fingers: [2, 0, 3, 3, 3, 0],
      barres: [7],
    },
    { frets: [2, 2, 4, 2, 3, 2], fingers: [1, 1, 3, 1, 2, 1], barres: [2] },
    {
      frets: [null, null, 4, 4, 3, 5],
      fingers: [0, 0, 2, 3, 1, 4],
      barres: [],
    },
    { frets: [7, 9, 7, 7, 7, 7], fingers: [1, 3, 1, 1, 1, 1], barres: [7] },
    {
      frets: [null, 9, 9, 11, 10, 10],
      fingers: [0, 1, 1, 4, 2, 3],
      barres: [9],
    },
  ],
  "B:m7b5": [
    {
      frets: [null, 2, 3, 2, 3, null],
      fingers: [0, 1, 3, 2, 4, 0],
      barres: [],
    },
    {
      frets: [7, null, 7, 7, 6, null],
      fingers: [2, 0, 3, 4, 1, 0],
      barres: [],
    },
    { frets: [7, 8, 9, 7, 10, 7], fingers: [1, 2, 3, 1, 4, 1], barres: [7] },
    {
      frets: [null, null, 9, 10, 10, 10],
      fingers: [0, 0, 1, 2, 2, 2],
      barres: [10],
    },
  ],
  "B:add9": [
    {
      frets: [null, 2, 1, null, 2, 2],
      fingers: [0, 2, 1, 0, 3, 4],
      barres: [],
    },
    { frets: [7, 6, null, 6, 7, 7], fingers: [3, 1, 0, 2, 4, 4], barres: [7] },
    {
      frets: [null, null, 9, 8, 7, 9],
      fingers: [0, 0, 3, 2, 1, 4],
      barres: [],
    },
    {
      frets: [null, 14, 13, 11, 14, 11],
      fingers: [0, 3, 2, 1, 4, 1],
      barres: [11],
    },
  ],
};
