// Imported from tombatossals/chords-db at df06fa7b425cf5fd29485ff6591236b3557e3fac.
// MIT © 2016 David Rubert. See public/licenses/chords-db.txt.
// Generated by scripts/import-ukulele-library.mjs. Frets/barres are absolute.
export type LibraryPosition = {
  frets: (number | null)[];
  fingers: number[];
  barres: number[];
};
export const LIBRARY_REVISION = "df06fa7b425cf5fd29485ff6591236b3557e3fac";
export const UKULELE_SHAPES: Record<string, LibraryPosition[]> = {
  "A:major": [
    {
      frets: [2, 1, 0, 0],
      fingers: [2, 1, 0, 0],
      barres: [],
    },
    {
      frets: [2, 4, 5, 4],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
    {
      frets: [6, 4, 5, 4],
      fingers: [4, 1, 2, 1],
      barres: [4],
    },
    {
      frets: [9, 9, 9, 12],
      fingers: [1, 1, 1, 4],
      barres: [9],
    },
  ],
  "A:minor": [
    {
      frets: [2, 0, 0, 0],
      fingers: [2, 0, 0, 0],
      barres: [],
    },
    {
      frets: [2, 0, 0, 3],
      fingers: [2, 0, 0, 3],
      barres: [],
    },
    {
      frets: [2, 4, 5, 3],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [5, 4, 5, 3],
      fingers: [3, 2, 4, 1],
      barres: [],
    },
  ],
  "A:dim": [
    {
      frets: [2, 3, 5, 3],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
    {
      frets: [5, 3, 5, 3],
      fingers: [3, 1, 4, 1],
      barres: [3],
    },
    {
      frets: [8, 9, 8, 6],
      fingers: [2, 4, 3, 1],
      barres: [],
    },
    {
      frets: [14, 12, 11, 12],
      fingers: [4, 2, 1, 3],
      barres: [],
    },
  ],
  "A:dim7": [
    {
      frets: [2, 3, 2, 3],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [5, 6, 5, 6],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [8, 9, 8, 9],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [11, 12, 11, 12],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "A:sus2": [
    {
      frets: [2, 4, 5, 2],
      fingers: [1, 3, 4, 1],
      barres: [2],
    },
    {
      frets: [4, 4, 5, 7],
      fingers: [1, 1, 2, 4],
      barres: [4],
    },
    {
      frets: [9, 9, 7, 7],
      fingers: [3, 4, 1, 1],
      barres: [7],
    },
    {
      frets: [9, 11, 12, 12],
      fingers: [1, 2, 3, 3],
      barres: [12],
    },
  ],
  "A:sus4": [
    {
      frets: [2, 2, 0, 0],
      fingers: [2, 3, 0, 0],
      barres: [],
    },
    {
      frets: [2, 4, 5, 5],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [7, 4, 5, 5],
      fingers: [4, 1, 2, 2],
      barres: [5],
    },
    {
      frets: [7, 4, 5, 7],
      fingers: [3, 1, 2, 4],
      barres: [],
    },
  ],
  "A:aug": [
    {
      frets: [2, 1, 1, 0],
      fingers: [3, 1, 2, 0],
      barres: [],
    },
    {
      frets: [2, 1, 1, 4],
      fingers: [2, 1, 1, 4],
      barres: [1],
    },
    {
      frets: [2, 5, 5, 4],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [6, 5, 5, 8],
      fingers: [2, 1, 1, 4],
      barres: [5],
    },
  ],
  "A:6": [
    {
      frets: [2, 4, 2, 4],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [6, 6, 5, 7],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [9, 9, 9, 9],
      fingers: [1, 1, 1, 1],
      barres: [9],
    },
    {
      frets: [11, 13, 12, 12],
      fingers: [1, 4, 2, 3],
      barres: [],
    },
  ],
  "A:7": [
    {
      frets: [0, 1, 0, 0],
      fingers: [0, 1, 0, 0],
      barres: [],
    },
    {
      frets: [2, 4, 3, 4],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [6, 7, 5, 7],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [9, 9, 9, 10],
      fingers: [1, 1, 1, 2],
      barres: [9],
    },
  ],
  "A:maj7": [
    {
      frets: [1, 1, 0, 0],
      fingers: [1, 2, 0, 0],
      barres: [],
    },
    {
      frets: [2, 4, 4, 4],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [6, 8, 5, 7],
      fingers: [2, 4, 1, 3],
      barres: [],
    },
    {
      frets: [9, 9, 9, 11],
      fingers: [1, 1, 1, 3],
      barres: [9],
    },
  ],
  "A:m6": [
    {
      frets: [2, 4, 2, 3],
      fingers: [1, 3, 1, 2],
      barres: [2],
    },
    {
      frets: [5, 6, 5, 7],
      fingers: [1, 2, 1, 3],
      barres: [5],
    },
    {
      frets: [9, 9, 8, 9],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [11, 12, 12, 12],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
  ],
  "A:m7": [
    {
      frets: [0, 0, 0, 0],
      fingers: [0, 0, 0, 0],
      barres: [],
    },
    {
      frets: [2, 4, 3, 3],
      fingers: [1, 3, 2, 2],
      barres: [3],
    },
    {
      frets: [5, 7, 5, 7],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [9, 9, 8, 10],
      fingers: [2, 2, 1, 3],
      barres: [9],
    },
  ],
  "A:m7b5": [
    {
      frets: [2, 3, 3, 3],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [5, 7, 5, 6],
      fingers: [1, 3, 1, 2],
      barres: [5],
    },
    {
      frets: [8, 9, 8, 10],
      fingers: [1, 2, 1, 3],
      barres: [8],
    },
    {
      frets: [12, 12, 11, 12],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
  ],
  "A:add9": [
    {
      frets: [2, 1, 0, 2],
      fingers: [2, 1, 0, 3],
      barres: [],
    },
    {
      frets: [4, 4, 5, 4],
      fingers: [1, 1, 2, 1],
      barres: [4],
    },
    {
      frets: [6, 9, 7, 7],
      fingers: [1, 4, 2, 2],
      barres: [7],
    },
    {
      frets: [9, 11, 9, 12],
      fingers: [1, 3, 1, 4],
      barres: [9],
    },
  ],
  "Ab:major": [
    {
      frets: [1, 3, 4, 3],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
    {
      frets: [5, 3, 4, 3],
      fingers: [3, 1, 2, 1],
      barres: [3],
    },
    {
      frets: [5, 3, 4, 6],
      fingers: [3, 1, 2, 4],
      barres: [],
    },
    {
      frets: [8, 8, 8, 11],
      fingers: [1, 1, 1, 4],
      barres: [8],
    },
  ],
  "Ab:minor": [
    {
      frets: [1, 3, 4, 2],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [4, 3, 4, 2],
      fingers: [3, 2, 4, 1],
      barres: [],
    },
    {
      frets: [4, 3, 4, 6],
      fingers: [2, 1, 3, 4],
      barres: [],
    },
    {
      frets: [8, 8, 7, 6],
      fingers: [3, 4, 2, 1],
      barres: [],
    },
  ],
  "Ab:dim": [
    {
      frets: [1, 2, 4, 2],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
    {
      frets: [4, 2, 4, 2],
      fingers: [3, 1, 4, 1],
      barres: [2],
    },
    {
      frets: [7, 8, 7, 5],
      fingers: [2, 4, 3, 1],
      barres: [],
    },
    {
      frets: [13, 11, 10, 11],
      fingers: [4, 2, 1, 3],
      barres: [],
    },
  ],
  "Ab:dim7": [
    {
      frets: [1, 2, 1, 2],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [4, 5, 4, 5],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [7, 8, 7, 8],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [10, 11, 10, 11],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "Ab:sus2": [
    {
      frets: [1, 3, 4, 1],
      fingers: [1, 3, 4, 1],
      barres: [1],
    },
    {
      frets: [3, 3, 4, 6],
      fingers: [1, 1, 2, 4],
      barres: [3],
    },
    {
      frets: [8, 8, 6, 6],
      fingers: [3, 4, 1, 1],
      barres: [6],
    },
    {
      frets: [8, 10, 11, 11],
      fingers: [1, 2, 3, 3],
      barres: [11],
    },
  ],
  "Ab:sus4": [
    {
      frets: [1, 3, 4, 4],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [6, 3, 4, 4],
      fingers: [4, 1, 2, 2],
      barres: [4],
    },
    {
      frets: [6, 3, 4, 6],
      fingers: [3, 1, 2, 4],
      barres: [],
    },
    {
      frets: [6, 8, 9, 6],
      fingers: [1, 3, 4, 1],
      barres: [6],
    },
  ],
  "Ab:aug": [
    {
      frets: [1, 0, 0, 3],
      fingers: [1, 0, 0, 3],
      barres: [],
    },
    {
      frets: [1, 4, 4, 3],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [5, 4, 4, 3],
      fingers: [3, 2, 2, 1],
      barres: [4],
    },
    {
      frets: [5, 4, 4, 7],
      fingers: [2, 1, 1, 4],
      barres: [4],
    },
  ],
  "Ab:6": [
    {
      frets: [1, 3, 1, 3],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [5, 5, 4, 6],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [8, 8, 8, 8],
      fingers: [1, 1, 1, 1],
      barres: [8],
    },
    {
      frets: [10, 12, 11, 11],
      fingers: [1, 4, 2, 3],
      barres: [],
    },
  ],
  "Ab:7": [
    {
      frets: [1, 3, 2, 3],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [5, 6, 4, 6],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [8, 8, 8, 9],
      fingers: [1, 1, 1, 2],
      barres: [8],
    },
    {
      frets: [11, 12, 11, 11],
      fingers: [1, 2, 1, 1],
      barres: [11],
    },
  ],
  "Ab:maj7": [
    {
      frets: [1, 3, 3, 3],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [5, 7, 4, 6],
      fingers: [2, 4, 1, 3],
      barres: [],
    },
    {
      frets: [8, 8, 8, 10],
      fingers: [1, 1, 1, 3],
      barres: [8],
    },
    {
      frets: [13, 12, 11, 10],
      fingers: [4, 3, 2, 1],
      barres: [],
    },
  ],
  "Ab:m6": [
    {
      frets: [1, 3, 1, 2],
      fingers: [1, 3, 1, 2],
      barres: [1],
    },
    {
      frets: [4, 5, 4, 6],
      fingers: [1, 2, 1, 3],
      barres: [4],
    },
    {
      frets: [8, 8, 7, 8],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [10, 11, 11, 11],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
  ],
  "Ab:m7": [
    {
      frets: [1, 3, 2, 2],
      fingers: [1, 3, 2, 2],
      barres: [2],
    },
    {
      frets: [4, 6, 4, 6],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [8, 8, 7, 9],
      fingers: [2, 2, 1, 3],
      barres: [8],
    },
    {
      frets: [11, 11, 11, 11],
      fingers: [1, 1, 1, 1],
      barres: [11],
    },
  ],
  "Ab:m7b5": [
    {
      frets: [1, 2, 2, 2],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [4, 6, 4, 5],
      fingers: [1, 3, 1, 2],
      barres: [4],
    },
    {
      frets: [7, 8, 7, 9],
      fingers: [1, 2, 1, 3],
      barres: [7],
    },
    {
      frets: [11, 11, 10, 11],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
  ],
  "Ab:add9": [
    {
      frets: [3, 3, 4, 3],
      fingers: [1, 1, 2, 1],
      barres: [3],
    },
    {
      frets: [5, 8, 6, 6],
      fingers: [1, 4, 2, 2],
      barres: [6],
    },
    {
      frets: [8, 10, 8, 11],
      fingers: [1, 3, 1, 4],
      barres: [8],
    },
    {
      frets: [13, 12, 11, 13],
      fingers: [3, 2, 1, 4],
      barres: [],
    },
  ],
  "B:major": [
    {
      frets: [4, 3, 2, 2],
      fingers: [3, 2, 1, 1],
      barres: [2],
    },
    {
      frets: [4, 6, 7, 6],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
    {
      frets: [8, 6, 7, 6],
      fingers: [3, 1, 2, 1],
      barres: [6],
    },
    {
      frets: [11, 11, 11, 14],
      fingers: [1, 1, 1, 4],
      barres: [11],
    },
  ],
  "B:minor": [
    {
      frets: [4, 2, 2, 2],
      fingers: [3, 1, 1, 1],
      barres: [2],
    },
    {
      frets: [4, 2, 2, 5],
      fingers: [3, 1, 1, 4],
      barres: [2],
    },
    {
      frets: [4, 6, 7, 5],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [7, 6, 7, 5],
      fingers: [3, 2, 4, 1],
      barres: [],
    },
  ],
  "B:dim": [
    {
      frets: [4, 2, 1, 2],
      fingers: [4, 2, 1, 3],
      barres: [],
    },
    {
      frets: [4, 5, 7, 5],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
    {
      frets: [7, 5, 7, 5],
      fingers: [3, 1, 4, 1],
      barres: [5],
    },
    {
      frets: [10, 11, 10, 8],
      fingers: [2, 4, 3, 1],
      barres: [],
    },
  ],
  "B:dim7": [
    {
      frets: [1, 2, 1, 2],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [4, 5, 4, 5],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [7, 8, 7, 8],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [10, 11, 10, 11],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "B:sus2": [
    {
      frets: [4, 6, 7, 4],
      fingers: [1, 3, 4, 1],
      barres: [4],
    },
    {
      frets: [6, 6, 7, 9],
      fingers: [1, 1, 2, 4],
      barres: [6],
    },
    {
      frets: [11, 11, 9, 9],
      fingers: [3, 4, 1, 1],
      barres: [9],
    },
    {
      frets: [11, 13, 14, 14],
      fingers: [1, 2, 3, 3],
      barres: [14],
    },
  ],
  "B:sus4": [
    {
      frets: [4, 4, 2, 2],
      fingers: [3, 4, 1, 1],
      barres: [2],
    },
    {
      frets: [4, 6, 7, 7],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [9, 6, 7, 7],
      fingers: [4, 1, 2, 2],
      barres: [7],
    },
    {
      frets: [9, 6, 7, 9],
      fingers: [3, 1, 2, 4],
      barres: [],
    },
  ],
  "B:aug": [
    {
      frets: [0, 3, 3, 2],
      fingers: [0, 2, 3, 1],
      barres: [],
    },
    {
      frets: [4, 3, 3, 2],
      fingers: [3, 2, 2, 1],
      barres: [3],
    },
    {
      frets: [4, 3, 3, 6],
      fingers: [2, 1, 1, 4],
      barres: [3],
    },
    {
      frets: [4, 7, 7, 6],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
  ],
  "B:6": [
    {
      frets: [1, 3, 2, 2],
      fingers: [1, 4, 2, 3],
      barres: [],
    },
    {
      frets: [4, 6, 4, 6],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [8, 8, 7, 9],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [11, 11, 11, 11],
      fingers: [1, 1, 1, 1],
      barres: [11],
    },
  ],
  "B:7": [
    {
      frets: [2, 3, 2, 2],
      fingers: [1, 2, 1, 1],
      barres: [2],
    },
    {
      frets: [4, 6, 5, 6],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [8, 9, 7, 9],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [11, 11, 11, 12],
      fingers: [1, 1, 1, 2],
      barres: [11],
    },
  ],
  "B:maj7": [
    {
      frets: [4, 3, 2, 1],
      fingers: [4, 3, 2, 1],
      barres: [],
    },
    {
      frets: [3, 3, 2, 2],
      fingers: [2, 3, 1, 1],
      barres: [2],
    },
    {
      frets: [4, 6, 6, 6],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [8, 10, 7, 9],
      fingers: [2, 4, 1, 3],
      barres: [],
    },
  ],
  "B:m6": [
    {
      frets: [1, 2, 2, 2],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [4, 6, 4, 5],
      fingers: [1, 3, 1, 2],
      barres: [4],
    },
    {
      frets: [7, 8, 7, 9],
      fingers: [1, 2, 1, 3],
      barres: [7],
    },
    {
      frets: [11, 11, 10, 11],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
  ],
  "B:m7": [
    {
      frets: [2, 2, 2, 2],
      fingers: [1, 1, 1, 1],
      barres: [2],
    },
    {
      frets: [4, 6, 5, 5],
      fingers: [1, 3, 2, 2],
      barres: [5],
    },
    {
      frets: [7, 9, 7, 9],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [11, 11, 10, 12],
      fingers: [2, 2, 1, 3],
      barres: [11],
    },
  ],
  "B:m7b5": [
    {
      frets: [2, 2, 1, 2],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [4, 5, 5, 5],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [7, 9, 7, 8],
      fingers: [1, 3, 1, 2],
      barres: [7],
    },
    {
      frets: [10, 11, 10, 12],
      fingers: [1, 2, 1, 3],
      barres: [10],
    },
  ],
  "B:add9": [
    {
      frets: [4, 3, 2, 4],
      fingers: [3, 2, 1, 4],
      barres: [],
    },
    {
      frets: [6, 6, 7, 6],
      fingers: [1, 1, 2, 1],
      barres: [6],
    },
    {
      frets: [8, 11, 9, 9],
      fingers: [1, 4, 2, 2],
      barres: [9],
    },
    {
      frets: [11, 13, 11, 14],
      fingers: [1, 3, 1, 4],
      barres: [11],
    },
  ],
  "Bb:major": [
    {
      frets: [3, 2, 1, 1],
      fingers: [3, 2, 1, 1],
      barres: [1],
    },
    {
      frets: [3, 5, 6, 5],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
    {
      frets: [7, 5, 6, 5],
      fingers: [3, 1, 2, 1],
      barres: [5],
    },
    {
      frets: [10, 10, 10, 13],
      fingers: [1, 1, 1, 4],
      barres: [10],
    },
  ],
  "Bb:minor": [
    {
      frets: [3, 1, 1, 1],
      fingers: [3, 1, 1, 1],
      barres: [1],
    },
    {
      frets: [3, 1, 1, 4],
      fingers: [3, 1, 1, 4],
      barres: [1],
    },
    {
      frets: [3, 5, 6, 4],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [6, 5, 6, 4],
      fingers: [3, 2, 4, 1],
      barres: [],
    },
  ],
  "Bb:dim": [
    {
      frets: [3, 1, 0, 1],
      fingers: [3, 1, 0, 2],
      barres: [],
    },
    {
      frets: [3, 4, 6, 4],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
    {
      frets: [6, 4, 6, 4],
      fingers: [3, 1, 4, 1],
      barres: [4],
    },
    {
      frets: [9, 10, 9, 7],
      fingers: [2, 4, 3, 1],
      barres: [],
    },
  ],
  "Bb:dim7": [
    {
      frets: [0, 1, 0, 1],
      fingers: [0, 1, 0, 2],
      barres: [],
    },
    {
      frets: [3, 4, 3, 4],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [6, 7, 6, 7],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [9, 10, 9, 10],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "Bb:sus2": [
    {
      frets: [3, 5, 6, 3],
      fingers: [1, 3, 4, 1],
      barres: [3],
    },
    {
      frets: [5, 5, 6, 8],
      fingers: [1, 1, 2, 4],
      barres: [5],
    },
    {
      frets: [10, 10, 8, 8],
      fingers: [3, 4, 1, 1],
      barres: [8],
    },
    {
      frets: [10, 12, 13, 13],
      fingers: [1, 2, 3, 3],
      barres: [13],
    },
  ],
  "Bb:sus4": [
    {
      frets: [3, 3, 1, 1],
      fingers: [3, 4, 1, 1],
      barres: [1],
    },
    {
      frets: [3, 5, 6, 6],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [8, 5, 6, 6],
      fingers: [4, 1, 2, 2],
      barres: [6],
    },
    {
      frets: [8, 5, 6, 8],
      fingers: [3, 1, 2, 4],
      barres: [],
    },
  ],
  "Bb:aug": [
    {
      frets: [3, 2, 2, 1],
      fingers: [3, 2, 2, 1],
      barres: [2],
    },
    {
      frets: [3, 2, 2, 5],
      fingers: [2, 1, 1, 4],
      barres: [2],
    },
    {
      frets: [3, 6, 6, 5],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [7, 6, 6, 9],
      fingers: [2, 1, 1, 4],
      barres: [6],
    },
  ],
  "Bb:6": [
    {
      frets: [0, 2, 1, 1],
      fingers: [0, 2, 1, 1],
      barres: [1],
    },
    {
      frets: [3, 5, 3, 5],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [7, 7, 6, 8],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [10, 10, 10, 10],
      fingers: [1, 1, 1, 1],
      barres: [10],
    },
  ],
  "Bb:7": [
    {
      frets: [1, 2, 1, 1],
      fingers: [1, 2, 1, 1],
      barres: [1],
    },
    {
      frets: [3, 5, 4, 5],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [7, 8, 6, 8],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [10, 10, 10, 11],
      fingers: [1, 1, 1, 2],
      barres: [10],
    },
  ],
  "Bb:maj7": [
    {
      frets: [3, 2, 1, 0],
      fingers: [3, 2, 1, 0],
      barres: [],
    },
    {
      frets: [2, 2, 1, 1],
      fingers: [2, 3, 1, 1],
      barres: [1],
    },
    {
      frets: [3, 5, 5, 5],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [7, 9, 6, 8],
      fingers: [2, 4, 1, 3],
      barres: [],
    },
  ],
  "Bb:m6": [
    {
      frets: [0, 1, 1, 1],
      fingers: [0, 1, 2, 3],
      barres: [],
    },
    {
      frets: [3, 5, 3, 4],
      fingers: [1, 3, 1, 2],
      barres: [3],
    },
    {
      frets: [6, 7, 6, 8],
      fingers: [1, 2, 1, 3],
      barres: [6],
    },
    {
      frets: [10, 10, 9, 10],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
  ],
  "Bb:m7": [
    {
      frets: [1, 1, 1, 1],
      fingers: [1, 1, 1, 1],
      barres: [1],
    },
    {
      frets: [3, 5, 4, 4],
      fingers: [1, 3, 2, 2],
      barres: [4],
    },
    {
      frets: [6, 8, 6, 8],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [10, 10, 9, 11],
      fingers: [2, 2, 1, 3],
      barres: [10],
    },
  ],
  "Bb:m7b5": [
    {
      frets: [1, 1, 0, 1],
      fingers: [1, 2, 0, 3],
      barres: [],
    },
    {
      frets: [3, 4, 4, 4],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [6, 8, 6, 7],
      fingers: [1, 3, 1, 2],
      barres: [6],
    },
    {
      frets: [9, 10, 9, 11],
      fingers: [1, 2, 1, 3],
      barres: [9],
    },
  ],
  "Bb:add9": [
    {
      frets: [3, 2, 1, 3],
      fingers: [3, 2, 1, 4],
      barres: [],
    },
    {
      frets: [5, 5, 6, 5],
      fingers: [1, 1, 2, 1],
      barres: [5],
    },
    {
      frets: [7, 10, 8, 8],
      fingers: [1, 4, 2, 2],
      barres: [8],
    },
    {
      frets: [10, 12, 10, 13],
      fingers: [1, 3, 1, 4],
      barres: [10],
    },
  ],
  "C:major": [
    {
      frets: [0, 0, 0, 3],
      fingers: [0, 0, 0, 3],
      barres: [],
    },
    {
      frets: [0, 4, 3, 3],
      fingers: [0, 2, 1, 1],
      barres: [3],
    },
    {
      frets: [5, 4, 3, 3],
      fingers: [3, 2, 1, 1],
      barres: [3],
    },
    {
      frets: [5, 7, 8, 7],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
  ],
  "C:minor": [
    {
      frets: [0, 3, 3, 3],
      fingers: [0, 1, 2, 3],
      barres: [],
    },
    {
      frets: [5, 3, 3, 3],
      fingers: [3, 1, 1, 1],
      barres: [3],
    },
    {
      frets: [5, 3, 3, 6],
      fingers: [3, 1, 1, 4],
      barres: [3],
    },
    {
      frets: [5, 7, 8, 6],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
  ],
  "C:dim": [
    {
      frets: [5, 3, 2, 3],
      fingers: [4, 2, 1, 3],
      barres: [],
    },
    {
      frets: [5, 6, 8, 6],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
    {
      frets: [8, 6, 8, 6],
      fingers: [3, 1, 4, 1],
      barres: [6],
    },
    {
      frets: [11, 12, 11, 9],
      fingers: [2, 4, 3, 1],
      barres: [],
    },
  ],
  "C:dim7": [
    {
      frets: [2, 3, 2, 3],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [5, 6, 5, 6],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [8, 9, 8, 9],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [11, 12, 11, 12],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "C:sus2": [
    {
      frets: [0, 2, 3, 3],
      fingers: [0, 1, 2, 2],
      barres: [3],
    },
    {
      frets: [5, 7, 8, 5],
      fingers: [1, 3, 4, 1],
      barres: [5],
    },
    {
      frets: [7, 7, 8, 10],
      fingers: [1, 1, 2, 4],
      barres: [7],
    },
    {
      frets: [12, 12, 10, 10],
      fingers: [3, 4, 1, 1],
      barres: [10],
    },
  ],
  "C:sus4": [
    {
      frets: [0, 0, 1, 3],
      fingers: [0, 0, 1, 3],
      barres: [],
    },
    {
      frets: [5, 5, 3, 3],
      fingers: [2, 3, 1, 1],
      barres: [3],
    },
    {
      frets: [5, 7, 8, 8],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [10, 7, 8, 10],
      fingers: [3, 1, 2, 4],
      barres: [],
    },
  ],
  "C:aug": [
    {
      frets: [1, 0, 0, 3],
      fingers: [1, 0, 0, 4],
      barres: [],
    },
    {
      frets: [1, 4, 4, 3],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [5, 4, 4, 3],
      fingers: [4, 2, 3, 1],
      barres: [],
    },
    {
      frets: [5, 4, 4, 7],
      fingers: [2, 1, 1, 4],
      barres: [4],
    },
  ],
  "C:6": [
    {
      frets: [0, 0, 0, 0],
      fingers: [0, 0, 0, 0],
      barres: [],
    },
    {
      frets: [2, 4, 3, 3],
      fingers: [1, 4, 2, 3],
      barres: [],
    },
    {
      frets: [5, 7, 5, 7],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [9, 9, 8, 10],
      fingers: [2, 2, 1, 3],
      barres: [9],
    },
  ],
  "C:7": [
    {
      frets: [0, 0, 0, 1],
      fingers: [0, 0, 0, 1],
      barres: [],
    },
    {
      frets: [3, 4, 3, 3],
      fingers: [1, 2, 1, 1],
      barres: [3],
    },
    {
      frets: [5, 7, 6, 7],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [9, 10, 8, 10],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
  ],
  "C:maj7": [
    {
      frets: [0, 0, 0, 2],
      fingers: [0, 0, 0, 2],
      barres: [],
    },
    {
      frets: [5, 4, 3, 2],
      fingers: [4, 3, 2, 1],
      barres: [],
    },
    {
      frets: [4, 4, 3, 3],
      fingers: [2, 3, 1, 1],
      barres: [3],
    },
    {
      frets: [5, 7, 7, 7],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
  ],
  "C:m6": [
    {
      frets: [2, 3, 3, 3],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [5, 7, 5, 6],
      fingers: [1, 3, 1, 2],
      barres: [5],
    },
    {
      frets: [8, 9, 8, 10],
      fingers: [1, 2, 1, 3],
      barres: [8],
    },
    {
      frets: [12, 12, 11, 12],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
  ],
  "C:m7": [
    {
      frets: [3, 3, 3, 3],
      fingers: [1, 1, 1, 1],
      barres: [3],
    },
    {
      frets: [5, 7, 6, 6],
      fingers: [1, 3, 2, 2],
      barres: [6],
    },
    {
      frets: [8, 10, 8, 10],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [12, 12, 11, 13],
      fingers: [2, 2, 1, 3],
      barres: [12],
    },
  ],
  "C:m7b5": [
    {
      frets: [3, 3, 2, 3],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [5, 6, 6, 6],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [8, 10, 8, 9],
      fingers: [1, 3, 1, 2],
      barres: [8],
    },
    {
      frets: [11, 12, 11, 13],
      fingers: [1, 2, 1, 3],
      barres: [11],
    },
  ],
  "C:add9": [
    {
      frets: [0, 2, 0, 3],
      fingers: [0, 2, 0, 3],
      barres: [],
    },
    {
      frets: [5, 4, 3, 5],
      fingers: [3, 2, 1, 4],
      barres: [],
    },
    {
      frets: [7, 7, 8, 7],
      fingers: [1, 1, 2, 1],
      barres: [7],
    },
    {
      frets: [9, 12, 10, 10],
      fingers: [1, 4, 2, 2],
      barres: [10],
    },
  ],
  "D:major": [
    {
      frets: [2, 2, 2, 0],
      fingers: [1, 2, 3, 0],
      barres: [],
    },
    {
      frets: [2, 2, 2, 5],
      fingers: [1, 1, 1, 4],
      barres: [2],
    },
    {
      frets: [7, 6, 5, 5],
      fingers: [3, 2, 1, 1],
      barres: [5],
    },
    {
      frets: [7, 9, 10, 9],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
  ],
  "D:minor": [
    {
      frets: [2, 2, 1, 0],
      fingers: [2, 3, 1, 0],
      barres: [],
    },
    {
      frets: [2, 5, 5, 5],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [7, 5, 5, 5],
      fingers: [3, 1, 1, 1],
      barres: [5],
    },
    {
      frets: [7, 5, 5, 8],
      fingers: [3, 1, 1, 4],
      barres: [5],
    },
  ],
  "D:dim": [
    {
      frets: [7, 5, 4, 5],
      fingers: [4, 2, 1, 3],
      barres: [],
    },
    {
      frets: [7, 8, 10, 8],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
    {
      frets: [10, 8, 10, 8],
      fingers: [3, 1, 4, 1],
      barres: [8],
    },
    {
      frets: [13, 14, 13, 11],
      fingers: [2, 4, 3, 1],
      barres: [],
    },
  ],
  "D:dim7": [
    {
      frets: [1, 2, 1, 2],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [4, 5, 4, 5],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [7, 8, 7, 8],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [10, 11, 10, 11],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "D:sus2": [
    {
      frets: [2, 4, 5, 5],
      fingers: [1, 2, 3, 3],
      barres: [5],
    },
    {
      frets: [7, 9, 10, 7],
      fingers: [1, 3, 4, 1],
      barres: [7],
    },
    {
      frets: [9, 9, 10, 12],
      fingers: [1, 1, 2, 4],
      barres: [9],
    },
    {
      frets: [14, 14, 12, 12],
      fingers: [3, 4, 1, 1],
      barres: [12],
    },
  ],
  "D:sus4": [
    {
      frets: [0, 2, 3, 0],
      fingers: [0, 2, 3, 0],
      barres: [],
    },
    {
      frets: [2, 2, 3, 0],
      fingers: [1, 2, 3, 0],
      barres: [],
    },
    {
      frets: [2, 2, 3, 5],
      fingers: [1, 1, 2, 4],
      barres: [2],
    },
    {
      frets: [7, 7, 5, 5],
      fingers: [3, 4, 1, 1],
      barres: [5],
    },
  ],
  "D:aug": [
    {
      frets: [3, 2, 2, 1],
      fingers: [3, 2, 2, 1],
      barres: [2],
    },
    {
      frets: [3, 2, 2, 5],
      fingers: [2, 1, 1, 4],
      barres: [2],
    },
    {
      frets: [3, 6, 6, 5],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [7, 6, 6, 9],
      fingers: [2, 1, 1, 4],
      barres: [6],
    },
  ],
  "D:6": [
    {
      frets: [2, 2, 2, 2],
      fingers: [1, 1, 1, 1],
      barres: [2],
    },
    {
      frets: [4, 6, 5, 5],
      fingers: [1, 4, 2, 3],
      barres: [],
    },
    {
      frets: [7, 9, 7, 9],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [11, 11, 10, 12],
      fingers: [2, 2, 1, 3],
      barres: [11],
    },
  ],
  "D:7": [
    {
      frets: [2, 2, 2, 3],
      fingers: [1, 1, 1, 2],
      barres: [2],
    },
    {
      frets: [5, 6, 5, 5],
      fingers: [1, 2, 1, 1],
      barres: [5],
    },
    {
      frets: [7, 9, 8, 9],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [11, 12, 10, 12],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
  ],
  "D:maj7": [
    {
      frets: [2, 2, 2, 4],
      fingers: [1, 1, 1, 3],
      barres: [2],
    },
    {
      frets: [7, 6, 5, 4],
      fingers: [4, 3, 2, 1],
      barres: [],
    },
    {
      frets: [6, 6, 5, 5],
      fingers: [2, 3, 1, 1],
      barres: [5],
    },
    {
      frets: [7, 9, 9, 9],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
  ],
  "D:m6": [
    {
      frets: [2, 2, 1, 2],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [4, 5, 5, 5],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [7, 9, 7, 8],
      fingers: [1, 3, 1, 2],
      barres: [7],
    },
    {
      frets: [10, 11, 10, 12],
      fingers: [1, 2, 1, 3],
      barres: [10],
    },
  ],
  "D:m7": [
    {
      frets: [2, 2, 1, 3],
      fingers: [2, 2, 1, 3],
      barres: [2],
    },
    {
      frets: [5, 5, 5, 5],
      fingers: [1, 1, 1, 1],
      barres: [5],
    },
    {
      frets: [7, 9, 8, 8],
      fingers: [1, 3, 2, 2],
      barres: [8],
    },
    {
      frets: [10, 12, 10, 12],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "D:m7b5": [
    {
      frets: [1, 2, 1, 3],
      fingers: [1, 2, 1, 3],
      barres: [1],
    },
    {
      frets: [5, 5, 4, 5],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [7, 8, 8, 8],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [10, 12, 10, 11],
      fingers: [1, 3, 1, 2],
      barres: [10],
    },
  ],
  "D:add9": [
    {
      frets: [2, 4, 2, 5],
      fingers: [1, 3, 1, 4],
      barres: [2],
    },
    {
      frets: [7, 6, 5, 7],
      fingers: [3, 2, 1, 4],
      barres: [],
    },
    {
      frets: [9, 9, 10, 9],
      fingers: [1, 1, 2, 1],
      barres: [9],
    },
    {
      frets: [11, 14, 12, 12],
      fingers: [1, 4, 2, 2],
      barres: [12],
    },
  ],
  "Db:major": [
    {
      frets: [1, 1, 1, 4],
      fingers: [1, 1, 1, 4],
      barres: [1],
    },
    {
      frets: [6, 5, 4, 4],
      fingers: [3, 2, 1, 1],
      barres: [4],
    },
    {
      frets: [6, 8, 9, 8],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
    {
      frets: [10, 8, 9, 8],
      fingers: [3, 1, 2, 1],
      barres: [8],
    },
  ],
  "Db:minor": [
    {
      frets: [1, 4, 4, 4],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [6, 4, 4, 4],
      fingers: [2, 1, 1, 1],
      barres: [4],
    },
    {
      frets: [6, 4, 4, 7],
      fingers: [3, 1, 1, 4],
      barres: [4],
    },
    {
      frets: [6, 8, 9, 7],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
  ],
  "Db:dim": [
    {
      frets: [6, 4, 3, 4],
      fingers: [4, 2, 1, 3],
      barres: [],
    },
    {
      frets: [6, 7, 9, 7],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
    {
      frets: [9, 7, 9, 7],
      fingers: [3, 1, 4, 1],
      barres: [7],
    },
    {
      frets: [12, 13, 12, 10],
      fingers: [2, 4, 3, 1],
      barres: [],
    },
  ],
  "Db:dim7": [
    {
      frets: [0, 1, 0, 1],
      fingers: [0, 1, 0, 2],
      barres: [],
    },
    {
      frets: [3, 4, 3, 4],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [6, 7, 6, 7],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [9, 10, 9, 10],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "Db:sus2": [
    {
      frets: [1, 3, 4, 4],
      fingers: [1, 2, 3, 3],
      barres: [4],
    },
    {
      frets: [6, 8, 9, 6],
      fingers: [1, 3, 4, 1],
      barres: [6],
    },
    {
      frets: [8, 8, 9, 11],
      fingers: [1, 1, 2, 4],
      barres: [8],
    },
    {
      frets: [13, 13, 11, 11],
      fingers: [3, 4, 1, 1],
      barres: [11],
    },
  ],
  "Db:sus4": [
    {
      frets: [1, 1, 2, 4],
      fingers: [1, 1, 2, 4],
      barres: [1],
    },
    {
      frets: [6, 6, 4, 4],
      fingers: [3, 4, 1, 1],
      barres: [4],
    },
    {
      frets: [6, 8, 9, 9],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [11, 8, 9, 11],
      fingers: [3, 1, 2, 4],
      barres: [],
    },
  ],
  "Db:aug": [
    {
      frets: [2, 1, 1, 0],
      fingers: [3, 1, 2, 0],
      barres: [],
    },
    {
      frets: [2, 1, 1, 4],
      fingers: [2, 1, 1, 4],
      barres: [1],
    },
    {
      frets: [2, 5, 5, 4],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [6, 5, 5, 4],
      fingers: [4, 2, 3, 1],
      barres: [],
    },
  ],
  "Db:6": [
    {
      frets: [1, 1, 1, 1],
      fingers: [1, 1, 1, 1],
      barres: [1],
    },
    {
      frets: [3, 5, 4, 4],
      fingers: [1, 4, 2, 3],
      barres: [],
    },
    {
      frets: [6, 8, 6, 8],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [10, 10, 9, 11],
      fingers: [2, 2, 1, 3],
      barres: [10],
    },
  ],
  "Db:7": [
    {
      frets: [1, 1, 1, 2],
      fingers: [1, 1, 1, 2],
      barres: [1],
    },
    {
      frets: [4, 5, 4, 4],
      fingers: [1, 2, 1, 1],
      barres: [4],
    },
    {
      frets: [6, 8, 7, 8],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [10, 11, 9, 11],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
  ],
  "Db:maj7": [
    {
      frets: [1, 1, 1, 3],
      fingers: [1, 1, 1, 3],
      barres: [1],
    },
    {
      frets: [5, 5, 4, 4],
      fingers: [2, 3, 1, 1],
      barres: [4],
    },
    {
      frets: [6, 5, 4, 3],
      fingers: [4, 3, 2, 1],
      barres: [],
    },
    {
      frets: [6, 8, 8, 8],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
  ],
  "Db:m6": [
    {
      frets: [1, 1, 0, 1],
      fingers: [1, 2, 0, 3],
      barres: [],
    },
    {
      frets: [3, 4, 4, 4],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [6, 8, 6, 7],
      fingers: [1, 3, 1, 2],
      barres: [6],
    },
    {
      frets: [9, 10, 9, 11],
      fingers: [1, 2, 1, 3],
      barres: [9],
    },
  ],
  "Db:m7": [
    {
      frets: [1, 1, 0, 2],
      fingers: [1, 2, 0, 3],
      barres: [],
    },
    {
      frets: [4, 4, 4, 4],
      fingers: [1, 1, 1, 1],
      barres: [4],
    },
    {
      frets: [6, 8, 7, 7],
      fingers: [1, 3, 2, 2],
      barres: [7],
    },
    {
      frets: [9, 11, 9, 11],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "Db:m7b5": [
    {
      frets: [0, 1, 0, 2],
      fingers: [0, 1, 0, 2],
      barres: [],
    },
    {
      frets: [4, 4, 3, 4],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [6, 7, 7, 7],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [9, 11, 9, 10],
      fingers: [1, 3, 1, 2],
      barres: [9],
    },
  ],
  "Db:add9": [
    {
      frets: [1, 3, 1, 4],
      fingers: [1, 3, 1, 4],
      barres: [1],
    },
    {
      frets: [6, 5, 4, 6],
      fingers: [3, 2, 1, 4],
      barres: [],
    },
    {
      frets: [8, 8, 9, 8],
      fingers: [1, 1, 2, 1],
      barres: [8],
    },
    {
      frets: [10, 13, 11, 11],
      fingers: [1, 4, 2, 2],
      barres: [11],
    },
  ],
  "E:major": [
    {
      frets: [1, 4, 0, 2],
      fingers: [1, 4, 0, 2],
      barres: [],
    },
    {
      frets: [4, 4, 4, 2],
      fingers: [2, 3, 4, 1],
      barres: [],
    },
    {
      frets: [4, 4, 4, 7],
      fingers: [1, 1, 1, 4],
      barres: [4],
    },
    {
      frets: [9, 8, 7, 7],
      fingers: [4, 3, 1, 1],
      barres: [7],
    },
  ],
  "E:minor": [
    {
      frets: [0, 4, 3, 2],
      fingers: [0, 3, 2, 1],
      barres: [],
    },
    {
      frets: [4, 4, 3, 2],
      fingers: [3, 4, 2, 1],
      barres: [],
    },
    {
      frets: [4, 7, 7, 7],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [9, 7, 7, 7],
      fingers: [3, 1, 1, 1],
      barres: [7],
    },
  ],
  "E:dim": [
    {
      frets: [3, 4, 3, 1],
      fingers: [2, 4, 3, 1],
      barres: [],
    },
    {
      frets: [9, 7, 6, 7],
      fingers: [4, 2, 1, 3],
      barres: [],
    },
    {
      frets: [9, 10, 12, 10],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
    {
      frets: [12, 10, 12, 10],
      fingers: [3, 1, 4, 1],
      barres: [10],
    },
  ],
  "E:dim7": [
    {
      frets: [0, 1, 0, 1],
      fingers: [0, 1, 0, 2],
      barres: [],
    },
    {
      frets: [3, 4, 3, 4],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [6, 7, 6, 7],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [9, 10, 9, 10],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "E:sus2": [
    {
      frets: [4, 4, 2, 2],
      fingers: [3, 4, 1, 1],
      barres: [2],
    },
    {
      frets: [4, 6, 7, 7],
      fingers: [1, 2, 3, 3],
      barres: [7],
    },
    {
      frets: [9, 11, 12, 9],
      fingers: [1, 3, 4, 1],
      barres: [9],
    },
    {
      frets: [11, 11, 12, 14],
      fingers: [1, 1, 2, 4],
      barres: [11],
    },
  ],
  "E:sus4": [
    {
      frets: [2, 4, 5, 2],
      fingers: [1, 2, 3, 1],
      barres: [2],
    },
    {
      frets: [4, 4, 5, 2],
      fingers: [2, 3, 4, 1],
      barres: [],
    },
    {
      frets: [4, 4, 5, 7],
      fingers: [1, 1, 2, 4],
      barres: [4],
    },
    {
      frets: [9, 9, 7, 7],
      fingers: [3, 4, 1, 1],
      barres: [7],
    },
  ],
  "E:aug": [
    {
      frets: [1, 0, 0, 3],
      fingers: [1, 0, 0, 3],
      barres: [],
    },
    {
      frets: [1, 4, 4, 3],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [5, 4, 4, 3],
      fingers: [3, 2, 2, 1],
      barres: [4],
    },
    {
      frets: [5, 4, 4, 7],
      fingers: [2, 1, 1, 4],
      barres: [4],
    },
  ],
  "E:6": [
    {
      frets: [1, 1, 0, 2],
      fingers: [1, 2, 0, 3],
      barres: [],
    },
    {
      frets: [4, 4, 4, 4],
      fingers: [1, 1, 1, 1],
      barres: [4],
    },
    {
      frets: [6, 8, 7, 7],
      fingers: [1, 4, 2, 3],
      barres: [],
    },
    {
      frets: [9, 11, 9, 11],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "E:7": [
    {
      frets: [1, 2, 0, 2],
      fingers: [1, 2, 0, 3],
      barres: [],
    },
    {
      frets: [4, 4, 4, 5],
      fingers: [1, 1, 1, 2],
      barres: [4],
    },
    {
      frets: [7, 8, 7, 7],
      fingers: [1, 2, 1, 1],
      barres: [7],
    },
    {
      frets: [9, 11, 10, 11],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "E:maj7": [
    {
      frets: [1, 3, 0, 2],
      fingers: [1, 3, 0, 2],
      barres: [],
    },
    {
      frets: [4, 4, 4, 6],
      fingers: [1, 1, 1, 3],
      barres: [4],
    },
    {
      frets: [9, 8, 7, 6],
      fingers: [4, 3, 2, 1],
      barres: [],
    },
    {
      frets: [8, 8, 7, 7],
      fingers: [2, 3, 1, 1],
      barres: [7],
    },
  ],
  "E:m6": [
    {
      frets: [0, 1, 0, 2],
      fingers: [0, 1, 0, 2],
      barres: [],
    },
    {
      frets: [4, 4, 3, 4],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [6, 7, 7, 7],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [9, 11, 9, 10],
      fingers: [1, 3, 1, 2],
      barres: [9],
    },
  ],
  "E:m7": [
    {
      frets: [0, 2, 0, 2],
      fingers: [0, 1, 0, 2],
      barres: [],
    },
    {
      frets: [4, 4, 3, 5],
      fingers: [2, 2, 1, 3],
      barres: [4],
    },
    {
      frets: [7, 7, 7, 7],
      fingers: [1, 1, 1, 1],
      barres: [7],
    },
    {
      frets: [9, 11, 10, 10],
      fingers: [1, 3, 2, 2],
      barres: [10],
    },
  ],
  "E:m7b5": [
    {
      frets: [0, 2, 0, 1],
      fingers: [0, 2, 0, 1],
      barres: [],
    },
    {
      frets: [3, 4, 3, 5],
      fingers: [1, 2, 1, 3],
      barres: [3],
    },
    {
      frets: [7, 7, 6, 7],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [9, 10, 10, 10],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
  ],
  "E:add9": [
    {
      frets: [1, 4, 2, 2],
      fingers: [1, 4, 2, 2],
      barres: [2],
    },
    {
      frets: [4, 6, 4, 7],
      fingers: [1, 3, 1, 4],
      barres: [4],
    },
    {
      frets: [9, 8, 7, 9],
      fingers: [3, 2, 1, 4],
      barres: [],
    },
    {
      frets: [11, 11, 12, 11],
      fingers: [1, 1, 2, 1],
      barres: [11],
    },
  ],
  "Eb:major": [
    {
      frets: [0, 3, 3, 1],
      fingers: [0, 3, 4, 1],
      barres: [],
    },
    {
      frets: [3, 3, 3, 1],
      fingers: [2, 3, 4, 1],
      barres: [],
    },
    {
      frets: [3, 3, 3, 6],
      fingers: [1, 1, 1, 4],
      barres: [3],
    },
    {
      frets: [8, 7, 6, 6],
      fingers: [3, 2, 1, 1],
      barres: [6],
    },
  ],
  "Eb:minor": [
    {
      frets: [3, 3, 2, 1],
      fingers: [3, 4, 2, 1],
      barres: [],
    },
    {
      frets: [3, 6, 6, 6],
      fingers: [1, 3, 3, 3],
      barres: [6],
    },
    {
      frets: [8, 6, 6, 6],
      fingers: [3, 1, 1, 1],
      barres: [6],
    },
    {
      frets: [8, 6, 6, 9],
      fingers: [3, 1, 1, 4],
      barres: [6],
    },
  ],
  "Eb:dim": [
    {
      frets: [2, 3, 2, 0],
      fingers: [1, 3, 2, 0],
      barres: [],
    },
    {
      frets: [8, 6, 5, 6],
      fingers: [4, 2, 1, 3],
      barres: [],
    },
    {
      frets: [8, 9, 11, 9],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
    {
      frets: [11, 9, 11, 9],
      fingers: [3, 1, 4, 1],
      barres: [9],
    },
  ],
  "Eb:dim7": [
    {
      frets: [2, 3, 2, 3],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [5, 6, 5, 6],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [8, 9, 8, 9],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [11, 12, 11, 12],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "Eb:sus2": [
    {
      frets: [3, 3, 1, 1],
      fingers: [3, 4, 1, 1],
      barres: [1],
    },
    {
      frets: [3, 5, 6, 6],
      fingers: [1, 2, 3, 3],
      barres: [6],
    },
    {
      frets: [8, 10, 11, 8],
      fingers: [1, 3, 4, 1],
      barres: [8],
    },
    {
      frets: [10, 10, 11, 13],
      fingers: [1, 1, 2, 4],
      barres: [10],
    },
  ],
  "Eb:sus4": [
    {
      frets: [1, 3, 4, 1],
      fingers: [1, 2, 3, 1],
      barres: [1],
    },
    {
      frets: [3, 3, 4, 1],
      fingers: [2, 3, 4, 1],
      barres: [],
    },
    {
      frets: [3, 3, 4, 6],
      fingers: [1, 1, 2, 4],
      barres: [3],
    },
    {
      frets: [8, 8, 6, 6],
      fingers: [3, 4, 1, 1],
      barres: [6],
    },
  ],
  "Eb:aug": [
    {
      frets: [0, 3, 3, 2],
      fingers: [0, 3, 2, 1],
      barres: [],
    },
    {
      frets: [4, 3, 3, 2],
      fingers: [3, 2, 2, 1],
      barres: [3],
    },
    {
      frets: [4, 3, 3, 6],
      fingers: [2, 1, 1, 4],
      barres: [3],
    },
    {
      frets: [4, 7, 7, 6],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
  ],
  "Eb:6": [
    {
      frets: [3, 3, 3, 3],
      fingers: [1, 1, 1, 1],
      barres: [3],
    },
    {
      frets: [5, 7, 6, 6],
      fingers: [1, 4, 2, 3],
      barres: [],
    },
    {
      frets: [8, 10, 8, 10],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [12, 12, 11, 13],
      fingers: [2, 2, 1, 3],
      barres: [12],
    },
  ],
  "Eb:7": [
    {
      frets: [3, 3, 3, 4],
      fingers: [1, 1, 1, 2],
      barres: [3],
    },
    {
      frets: [6, 7, 6, 6],
      fingers: [1, 2, 1, 1],
      barres: [6],
    },
    {
      frets: [8, 10, 9, 10],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [12, 13, 11, 13],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
  ],
  "Eb:maj7": [
    {
      frets: [3, 3, 3, 5],
      fingers: [1, 1, 1, 3],
      barres: [3],
    },
    {
      frets: [8, 7, 6, 5],
      fingers: [4, 3, 2, 1],
      barres: [],
    },
    {
      frets: [7, 7, 6, 6],
      fingers: [2, 3, 1, 1],
      barres: [6],
    },
    {
      frets: [8, 10, 10, 10],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
  ],
  "Eb:m6": [
    {
      frets: [3, 3, 2, 3],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [5, 6, 6, 6],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [8, 10, 8, 9],
      fingers: [1, 3, 1, 2],
      barres: [8],
    },
    {
      frets: [11, 12, 11, 13],
      fingers: [1, 2, 1, 3],
      barres: [11],
    },
  ],
  "Eb:m7": [
    {
      frets: [3, 3, 2, 4],
      fingers: [2, 2, 1, 3],
      barres: [3],
    },
    {
      frets: [6, 6, 6, 6],
      fingers: [1, 1, 1, 1],
      barres: [6],
    },
    {
      frets: [8, 10, 9, 9],
      fingers: [1, 3, 2, 2],
      barres: [9],
    },
    {
      frets: [11, 13, 11, 13],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "Eb:m7b5": [
    {
      frets: [2, 3, 2, 4],
      fingers: [1, 2, 1, 3],
      barres: [2],
    },
    {
      frets: [6, 6, 5, 6],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [8, 9, 9, 9],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [11, 13, 11, 12],
      fingers: [1, 3, 1, 2],
      barres: [11],
    },
  ],
  "Eb:add9": [
    {
      frets: [0, 3, 1, 1],
      fingers: [0, 3, 1, 1],
      barres: [1],
    },
    {
      frets: [3, 5, 3, 6],
      fingers: [1, 3, 1, 4],
      barres: [3],
    },
    {
      frets: [8, 7, 6, 8],
      fingers: [3, 2, 1, 4],
      barres: [],
    },
    {
      frets: [10, 10, 11, 10],
      fingers: [1, 1, 2, 1],
      barres: [10],
    },
  ],
  "F:major": [
    {
      frets: [2, 0, 1, 0],
      fingers: [2, 0, 1, 0],
      barres: [],
    },
    {
      frets: [2, 0, 1, 3],
      fingers: [2, 0, 1, 3],
      barres: [],
    },
    {
      frets: [5, 5, 5, 8],
      fingers: [1, 1, 1, 4],
      barres: [5],
    },
    {
      frets: [10, 9, 8, 8],
      fingers: [3, 2, 1, 1],
      barres: [8],
    },
  ],
  "F:minor": [
    {
      frets: [1, 0, 1, 3],
      fingers: [1, 0, 2, 4],
      barres: [],
    },
    {
      frets: [5, 5, 4, 3],
      fingers: [3, 4, 2, 1],
      barres: [],
    },
    {
      frets: [5, 8, 8, 8],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [10, 8, 8, 8],
      fingers: [3, 1, 1, 1],
      barres: [8],
    },
  ],
  "F:dim": [
    {
      frets: [4, 5, 4, 2],
      fingers: [2, 4, 3, 1],
      barres: [],
    },
    {
      frets: [10, 8, 7, 8],
      fingers: [4, 2, 1, 3],
      barres: [],
    },
    {
      frets: [10, 11, 13, 11],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
    {
      frets: [13, 11, 13, 11],
      fingers: [3, 1, 4, 1],
      barres: [11],
    },
  ],
  "F:dim7": [
    {
      frets: [1, 2, 1, 2],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [4, 5, 4, 5],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [7, 8, 7, 8],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [10, 11, 10, 11],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "F:sus2": [
    {
      frets: [0, 0, 1, 3],
      fingers: [0, 0, 1, 3],
      barres: [],
    },
    {
      frets: [5, 5, 3, 3],
      fingers: [3, 4, 1, 1],
      barres: [3],
    },
    {
      frets: [5, 7, 8, 8],
      fingers: [1, 2, 3, 3],
      barres: [8],
    },
    {
      frets: [10, 12, 13, 10],
      fingers: [1, 3, 4, 1],
      barres: [10],
    },
  ],
  "F:sus4": [
    {
      frets: [3, 0, 1, 1],
      fingers: [3, 0, 1, 1],
      barres: [1],
    },
    {
      frets: [3, 0, 1, 3],
      fingers: [2, 0, 1, 3],
      barres: [],
    },
    {
      frets: [3, 5, 6, 3],
      fingers: [1, 2, 3, 1],
      barres: [3],
    },
    {
      frets: [5, 5, 6, 3],
      fingers: [2, 3, 4, 1],
      barres: [],
    },
  ],
  "F:aug": [
    {
      frets: [2, 1, 1, 0],
      fingers: [3, 1, 2, 0],
      barres: [],
    },
    {
      frets: [2, 1, 1, 4],
      fingers: [2, 1, 1, 4],
      barres: [1],
    },
    {
      frets: [2, 5, 5, 4],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [6, 5, 5, 8],
      fingers: [2, 1, 1, 4],
      barres: [5],
    },
  ],
  "F:6": [
    {
      frets: [2, 2, 1, 3],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [5, 5, 5, 5],
      fingers: [1, 1, 1, 1],
      barres: [5],
    },
    {
      frets: [7, 9, 8, 8],
      fingers: [1, 4, 2, 3],
      barres: [],
    },
    {
      frets: [10, 12, 10, 12],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "F:7": [
    {
      frets: [2, 3, 1, 3],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [5, 5, 5, 6],
      fingers: [1, 1, 1, 2],
      barres: [5],
    },
    {
      frets: [8, 9, 8, 8],
      fingers: [1, 2, 1, 1],
      barres: [8],
    },
    {
      frets: [10, 12, 11, 12],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "F:maj7": [
    {
      frets: [2, 4, 1, 3],
      fingers: [2, 4, 1, 3],
      barres: [],
    },
    {
      frets: [5, 5, 5, 7],
      fingers: [1, 1, 1, 3],
      barres: [5],
    },
    {
      frets: [10, 9, 8, 7],
      fingers: [4, 3, 2, 1],
      barres: [],
    },
    {
      frets: [9, 9, 8, 8],
      fingers: [2, 3, 1, 1],
      barres: [8],
    },
  ],
  "F:m6": [
    {
      frets: [1, 2, 1, 3],
      fingers: [1, 2, 1, 3],
      barres: [1],
    },
    {
      frets: [5, 5, 4, 5],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [7, 8, 8, 8],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [10, 12, 10, 11],
      fingers: [1, 3, 1, 2],
      barres: [10],
    },
  ],
  "F:m7": [
    {
      frets: [1, 3, 1, 3],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [5, 5, 4, 6],
      fingers: [2, 2, 1, 3],
      barres: [5],
    },
    {
      frets: [8, 8, 8, 8],
      fingers: [1, 1, 1, 1],
      barres: [8],
    },
    {
      frets: [10, 12, 11, 11],
      fingers: [1, 3, 2, 2],
      barres: [11],
    },
  ],
  "F:m7b5": [
    {
      frets: [1, 3, 1, 2],
      fingers: [1, 3, 1, 2],
      barres: [1],
    },
    {
      frets: [4, 5, 4, 6],
      fingers: [1, 2, 1, 3],
      barres: [4],
    },
    {
      frets: [8, 8, 7, 8],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [10, 11, 11, 11],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
  ],
  "F:add9": [
    {
      frets: [0, 0, 1, 0],
      fingers: [0, 0, 1, 0],
      barres: [],
    },
    {
      frets: [2, 5, 3, 3],
      fingers: [1, 4, 2, 2],
      barres: [3],
    },
    {
      frets: [5, 7, 5, 8],
      fingers: [1, 3, 1, 4],
      barres: [5],
    },
    {
      frets: [10, 9, 8, 10],
      fingers: [3, 2, 1, 4],
      barres: [],
    },
  ],
  "G:major": [
    {
      frets: [0, 2, 3, 2],
      fingers: [0, 1, 3, 2],
      barres: [],
    },
    {
      frets: [4, 2, 3, 2],
      fingers: [3, 1, 2, 1],
      barres: [2],
    },
    {
      frets: [4, 2, 3, 5],
      fingers: [3, 1, 2, 4],
      barres: [],
    },
    {
      frets: [7, 7, 7, 10],
      fingers: [1, 1, 1, 4],
      barres: [7],
    },
  ],
  "G:minor": [
    {
      frets: [0, 2, 3, 1],
      fingers: [0, 2, 3, 1],
      barres: [],
    },
    {
      frets: [3, 2, 3, 1],
      fingers: [3, 2, 4, 1],
      barres: [],
    },
    {
      frets: [3, 2, 3, 5],
      fingers: [2, 1, 3, 4],
      barres: [],
    },
    {
      frets: [7, 7, 6, 5],
      fingers: [3, 4, 2, 1],
      barres: [],
    },
  ],
  "G:dim": [
    {
      frets: [0, 1, 3, 1],
      fingers: [0, 1, 3, 2],
      barres: [],
    },
    {
      frets: [3, 1, 3, 1],
      fingers: [3, 1, 4, 1],
      barres: [1],
    },
    {
      frets: [6, 7, 6, 4],
      fingers: [2, 4, 3, 1],
      barres: [],
    },
    {
      frets: [12, 10, 9, 10],
      fingers: [4, 2, 1, 3],
      barres: [],
    },
  ],
  "G:dim7": [
    {
      frets: [0, 1, 0, 1],
      fingers: [0, 1, 0, 2],
      barres: [],
    },
    {
      frets: [3, 4, 3, 4],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [6, 7, 6, 7],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [9, 10, 9, 10],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "G:sus2": [
    {
      frets: [0, 2, 3, 0],
      fingers: [0, 2, 3, 0],
      barres: [],
    },
    {
      frets: [2, 2, 3, 5],
      fingers: [1, 1, 2, 4],
      barres: [2],
    },
    {
      frets: [7, 7, 5, 5],
      fingers: [3, 4, 1, 1],
      barres: [5],
    },
    {
      frets: [7, 9, 10, 10],
      fingers: [1, 2, 3, 3],
      barres: [10],
    },
  ],
  "G:sus4": [
    {
      frets: [0, 2, 3, 3],
      fingers: [0, 1, 2, 3],
      barres: [],
    },
    {
      frets: [5, 2, 3, 3],
      fingers: [4, 1, 2, 2],
      barres: [3],
    },
    {
      frets: [5, 2, 3, 5],
      fingers: [3, 1, 2, 4],
      barres: [],
    },
    {
      frets: [5, 7, 8, 5],
      fingers: [1, 3, 4, 1],
      barres: [5],
    },
  ],
  "G:aug": [
    {
      frets: [0, 3, 3, 2],
      fingers: [0, 2, 3, 1],
      barres: [],
    },
    {
      frets: [4, 3, 3, 2],
      fingers: [3, 2, 2, 1],
      barres: [3],
    },
    {
      frets: [4, 3, 3, 6],
      fingers: [2, 1, 1, 4],
      barres: [3],
    },
    {
      frets: [4, 7, 7, 6],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
  ],
  "G:6": [
    {
      frets: [0, 2, 0, 2],
      fingers: [0, 1, 0, 2],
      barres: [],
    },
    {
      frets: [4, 4, 3, 5],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [7, 7, 7, 7],
      fingers: [1, 1, 1, 1],
      barres: [7],
    },
    {
      frets: [9, 11, 10, 10],
      fingers: [1, 4, 2, 3],
      barres: [],
    },
  ],
  "G:7": [
    {
      frets: [0, 2, 1, 2],
      fingers: [0, 2, 1, 3],
      barres: [],
    },
    {
      frets: [4, 5, 3, 5],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [7, 7, 7, 8],
      fingers: [1, 1, 1, 2],
      barres: [7],
    },
    {
      frets: [10, 11, 10, 10],
      fingers: [1, 2, 1, 1],
      barres: [10],
    },
  ],
  "G:maj7": [
    {
      frets: [0, 2, 2, 2],
      fingers: [0, 1, 2, 3],
      barres: [],
    },
    {
      frets: [4, 6, 3, 5],
      fingers: [2, 4, 1, 3],
      barres: [],
    },
    {
      frets: [7, 7, 7, 9],
      fingers: [1, 1, 1, 3],
      barres: [7],
    },
    {
      frets: [12, 11, 10, 9],
      fingers: [4, 3, 2, 1],
      barres: [],
    },
  ],
  "G:m6": [
    {
      frets: [0, 2, 0, 1],
      fingers: [0, 2, 0, 1],
      barres: [],
    },
    {
      frets: [3, 4, 3, 5],
      fingers: [1, 2, 1, 3],
      barres: [3],
    },
    {
      frets: [7, 7, 6, 7],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [9, 10, 10, 10],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
  ],
  "G:m7": [
    {
      frets: [0, 2, 1, 1],
      fingers: [0, 2, 1, 1],
      barres: [1],
    },
    {
      frets: [3, 5, 3, 5],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [7, 7, 6, 8],
      fingers: [2, 2, 1, 3],
      barres: [7],
    },
    {
      frets: [10, 10, 10, 10],
      fingers: [1, 1, 1, 1],
      barres: [10],
    },
  ],
  "G:m7b5": [
    {
      frets: [0, 1, 1, 1],
      fingers: [0, 1, 2, 3],
      barres: [],
    },
    {
      frets: [3, 5, 3, 4],
      fingers: [1, 3, 1, 2],
      barres: [3],
    },
    {
      frets: [6, 7, 6, 8],
      fingers: [1, 2, 1, 3],
      barres: [6],
    },
    {
      frets: [10, 10, 9, 10],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
  ],
  "G:add9": [
    {
      frets: [2, 2, 3, 2],
      fingers: [1, 1, 2, 1],
      barres: [2],
    },
    {
      frets: [4, 7, 5, 5],
      fingers: [1, 4, 2, 2],
      barres: [5],
    },
    {
      frets: [7, 9, 7, 10],
      fingers: [1, 3, 1, 4],
      barres: [7],
    },
    {
      frets: [12, 11, 10, 12],
      fingers: [3, 2, 1, 4],
      barres: [],
    },
  ],
  "Gb:major": [
    {
      frets: [3, 1, 2, 1],
      fingers: [3, 1, 2, 1],
      barres: [1],
    },
    {
      frets: [3, 1, 2, 4],
      fingers: [3, 1, 2, 4],
      barres: [],
    },
    {
      frets: [6, 6, 6, 9],
      fingers: [1, 1, 1, 4],
      barres: [6],
    },
    {
      frets: [11, 10, 9, 9],
      fingers: [3, 2, 1, 1],
      barres: [9],
    },
  ],
  "Gb:minor": [
    {
      frets: [2, 1, 2, 0],
      fingers: [2, 1, 3, 0],
      barres: [],
    },
    {
      frets: [2, 1, 2, 4],
      fingers: [2, 1, 3, 4],
      barres: [],
    },
    {
      frets: [6, 6, 5, 4],
      fingers: [3, 4, 2, 1],
      barres: [],
    },
    {
      frets: [11, 9, 9, 9],
      fingers: [3, 1, 1, 1],
      barres: [9],
    },
  ],
  "Gb:dim": [
    {
      frets: [2, 0, 2, 0],
      fingers: [2, 0, 3, 0],
      barres: [],
    },
    {
      frets: [5, 6, 5, 3],
      fingers: [2, 4, 3, 1],
      barres: [],
    },
    {
      frets: [11, 9, 8, 9],
      fingers: [4, 2, 1, 3],
      barres: [],
    },
    {
      frets: [11, 12, 14, 12],
      fingers: [1, 2, 4, 3],
      barres: [],
    },
  ],
  "Gb:dim7": [
    {
      frets: [2, 3, 2, 3],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [5, 6, 5, 6],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [8, 9, 8, 9],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [11, 12, 11, 12],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "Gb:sus2": [
    {
      frets: [1, 1, 2, 4],
      fingers: [1, 1, 2, 4],
      barres: [1],
    },
    {
      frets: [6, 6, 4, 4],
      fingers: [3, 4, 1, 1],
      barres: [4],
    },
    {
      frets: [6, 8, 9, 9],
      fingers: [1, 2, 3, 3],
      barres: [9],
    },
    {
      frets: [11, 13, 14, 11],
      fingers: [1, 3, 4, 1],
      barres: [11],
    },
  ],
  "Gb:sus4": [
    {
      frets: [4, 1, 2, 4],
      fingers: [3, 1, 2, 4],
      barres: [],
    },
    {
      frets: [4, 6, 7, 4],
      fingers: [1, 2, 3, 1],
      barres: [4],
    },
    {
      frets: [6, 6, 7, 4],
      fingers: [2, 3, 4, 1],
      barres: [],
    },
    {
      frets: [6, 6, 7, 9],
      fingers: [1, 1, 2, 4],
      barres: [6],
    },
  ],
  "Gb:aug": [
    {
      frets: [3, 2, 2, 1],
      fingers: [3, 2, 2, 1],
      barres: [2],
    },
    {
      frets: [3, 2, 2, 5],
      fingers: [2, 1, 1, 4],
      barres: [2],
    },
    {
      frets: [3, 6, 6, 5],
      fingers: [1, 3, 4, 2],
      barres: [],
    },
    {
      frets: [7, 6, 6, 9],
      fingers: [2, 1, 1, 4],
      barres: [6],
    },
  ],
  "Gb:6": [
    {
      frets: [3, 3, 2, 4],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [6, 6, 6, 6],
      fingers: [1, 1, 1, 1],
      barres: [6],
    },
    {
      frets: [8, 10, 9, 9],
      fingers: [1, 4, 2, 3],
      barres: [],
    },
    {
      frets: [11, 13, 11, 13],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "Gb:7": [
    {
      frets: [3, 4, 2, 4],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [6, 6, 6, 7],
      fingers: [1, 1, 1, 2],
      barres: [6],
    },
    {
      frets: [9, 10, 9, 9],
      fingers: [1, 2, 1, 1],
      barres: [9],
    },
    {
      frets: [11, 13, 12, 13],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
  ],
  "Gb:maj7": [
    {
      frets: [3, 5, 2, 4],
      fingers: [2, 4, 1, 3],
      barres: [],
    },
    {
      frets: [6, 6, 6, 8],
      fingers: [1, 1, 1, 3],
      barres: [6],
    },
    {
      frets: [11, 10, 9, 8],
      fingers: [4, 3, 2, 1],
      barres: [],
    },
    {
      frets: [10, 10, 9, 9],
      fingers: [2, 3, 1, 1],
      barres: [9],
    },
  ],
  "Gb:m6": [
    {
      frets: [2, 3, 2, 4],
      fingers: [1, 2, 1, 3],
      barres: [2],
    },
    {
      frets: [6, 6, 5, 6],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [8, 9, 9, 9],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
    {
      frets: [11, 13, 11, 12],
      fingers: [1, 3, 1, 2],
      barres: [11],
    },
  ],
  "Gb:m7": [
    {
      frets: [2, 4, 2, 4],
      fingers: [1, 3, 2, 4],
      barres: [],
    },
    {
      frets: [6, 6, 5, 7],
      fingers: [2, 2, 1, 3],
      barres: [6],
    },
    {
      frets: [9, 9, 9, 9],
      fingers: [1, 1, 1, 1],
      barres: [9],
    },
    {
      frets: [11, 13, 12, 12],
      fingers: [1, 3, 2, 2],
      barres: [12],
    },
  ],
  "Gb:m7b5": [
    {
      frets: [2, 4, 2, 3],
      fingers: [1, 3, 1, 2],
      barres: [2],
    },
    {
      frets: [5, 6, 5, 7],
      fingers: [1, 2, 1, 3],
      barres: [5],
    },
    {
      frets: [9, 9, 8, 9],
      fingers: [2, 3, 1, 4],
      barres: [],
    },
    {
      frets: [11, 12, 12, 12],
      fingers: [1, 2, 3, 4],
      barres: [],
    },
  ],
  "Gb:add9": [
    {
      frets: [1, 1, 2, 1],
      fingers: [1, 1, 2, 1],
      barres: [1],
    },
    {
      frets: [3, 6, 4, 4],
      fingers: [1, 4, 2, 2],
      barres: [4],
    },
    {
      frets: [6, 8, 6, 9],
      fingers: [1, 3, 1, 4],
      barres: [6],
    },
    {
      frets: [11, 10, 9, 11],
      fingers: [3, 2, 1, 4],
      barres: [],
    },
  ],
};
